import type { ModelBuilderId } from '../types';
import {
  layerTarget,
  partTarget,
  type FamilyExplanationRegistration,
  type StructureExplanationContent,
  type StructureExplanationTarget,
} from './types';

const family = (
  modelBuilder: ModelBuilderId,
  targets: readonly StructureExplanationTarget[],
  explanation: StructureExplanationContent,
): FamilyExplanationRegistration => ({ modelBuilder, targets, explanation });

export const EXPANDED_FAMILY_STRUCTURE_EXPLANATIONS: readonly FamilyExplanationRegistration[] =
  [
    family('lambda', [partTarget('capsid'), layerTarget('capsid')], {
      genericSummary: '람다 파지의 이중가닥 DNA를 감싸는 정이십면체 머리예요.',
      actualName: 'Lambda gpE major capsid protein shell',
      role: '조밀하게 포장된 dsDNA를 보호하고 portal·neck과 결합해 머리를 완성해요.',
      location: '긴 꼬리 위쪽의 다면체 머리',
      relationships: ['아래쪽 neck과 portal을 통해 비수축형 꼬리 관으로 이어져요.'],
      modelRepresentation: '각진 정이십면체 shell로 표시해요.',
      simplification: 'gpE 격자와 보조 capsid 단백질의 실제 수는 줄였어요.',
      evidence: 'observed',
      sourceIds: ['pdb-8iyd', 'pdb-8xqb'],
    }),
    family('lambda', [partTarget('capsomer')], {
      genericSummary: '람다 머리 표면의 반복 capsid 단백질 단위예요.',
      actualName: 'Lambda gpE capsomers',
      role: '반복 격자를 이루어 dsDNA를 감싸는 머리 shell을 만들어요.',
      location: '정이십면체 머리 표면',
      relationships: ['서로 맞물려 capsid를 이루고 한 꼭짓점의 portal과 접해요.'],
      modelRepresentation: 'capsid 표면의 작은 반복 기둥으로 표시해요.',
      simplification: 'hexon·penton 배치와 실제 화학량론은 시각적으로 줄였어요.',
      evidence: 'observed',
      sourceIds: ['pdb-8iyd'],
    }),
    family('lambda', [partTarget('genome'), layerTarget('genome')], {
      genericSummary: '람다 파지 머리 안에 포장되는 선형 이중가닥 DNA예요.',
      actualName: 'Lambda linear dsDNA genome',
      role: '감염 시 긴 비수축형 꼬리를 지나 세균 세포로 전달되는 유전정보를 담아요.',
      location: 'capsid 머리 내부',
      relationships: ['portal·tail tube가 DNA 방출 경로를 이뤄요.'],
      modelRepresentation: '머리 안쪽의 보라색 코일로 표시해요.',
      simplification: '실제 동심성 DNA 포장과 압력은 단일 코일로 줄였어요.',
      evidence: 'observed',
      sourceIds: ['pdb-8iyd'],
    }),
    family('lambda', [partTarget('neck')], {
      genericSummary: '람다 파지 머리와 비수축형 꼬리를 잇는 연결 복합체예요.',
      actualName: 'Lambda head–tail connector and neck',
      role: '완성된 머리와 꼬리를 결합하고 DNA 전달 축을 정렬해요.',
      location: 'capsid 아래와 긴 꼬리 위 사이',
      relationships: ['위쪽 portal과 아래쪽 tail tube를 이어줘요.'],
      modelRepresentation: '머리 아래의 짧은 원통과 고리로 표시해요.',
      simplification: 'connector의 개별 단백질 종류와 대칭 차이는 생략해요.',
      evidence: 'observed',
      sourceIds: ['pdb-8iyd', 'pdb-8xqb'],
    }),
    family('lambda', [partTarget('flexible-tail'), layerTarget('tail')], {
      genericSummary: '수축하지 않는 길고 유연한 람다 파지 꼬리 관이에요.',
      actualName: 'Lambda gpV non-contractile tail tube',
      role: '숙주 표면에서 capsid의 DNA가 이동할 통로를 만들어요.',
      location: 'neck 아래에서 말단 복합체까지',
      relationships: ['위쪽 head connector와 아래쪽 숙주 인식 부위를 연결해요.'],
      modelRepresentation: '완만하게 굽은 긴 관과 반복 고리로 표시해요.',
      simplification: 'gpV 반복 격자와 실제 유연성은 연속 관으로 줄였어요.',
      evidence: 'observed',
      sourceIds: ['pdb-8xqb'],
    }),
    family('lambda', [partTarget('tail-fiber')], {
      genericSummary: '람다 파지 꼬리 끝의 숙주 인식 부속 구조예요.',
      actualName: 'Lambda distal tail tip and side fibers',
      role: '세균 표면을 인식하고 꼬리 끝을 안정적으로 접촉시켜요.',
      location: '비수축형 꼬리의 distal end',
      relationships: ['tail tube 말단에 붙어 DNA 전달이 시작될 숙주 접점을 만들어요.'],
      modelRepresentation: '꼬리 끝에서 방사형으로 뻗는 가는 선으로 표시해요.',
      simplification: '수용체 결합 단백질의 분자 구조는 방향성만 남겼어요.',
      evidence: 'family-supported',
      sourceIds: ['pdb-8xqb'],
    }),

    family('t7', [partTarget('capsid'), layerTarget('capsid')], {
      genericSummary: 'T7의 이중가닥 DNA를 감싸는 정이십면체 머리예요.',
      actualName: 'T7 gp10 capsid shell',
      role: 'DNA를 보호하고 portal을 통해 짧은 꼬리 장치와 연결해요.',
      location: '짧은 꼬리 위쪽의 다면체 머리',
      relationships: ['한 꼭짓점의 portal이 내부 DNA와 꼬리 관을 이어줘요.'],
      modelRepresentation: '정이십면체 shell로 표시해요.',
      simplification: 'gp10 격자의 실제 반복 수와 보조 단백질은 줄였어요.',
      evidence: 'observed',
      sourceIds: ['pdb-3j7v', 'pdb-7ey7'],
    }),
    family('t7', [partTarget('capsomer')], {
      genericSummary: 'T7 capsid 표면을 이루는 gp10 반복 단위예요.',
      actualName: 'T7 gp10 capsomers',
      role: '반복 격자를 만들어 DNA를 둘러싼 capsid shell을 구성해요.',
      location: 'T7 머리 표면',
      relationships: ['서로 맞물려 capsid 면과 꼭짓점을 만들어요.'],
      modelRepresentation: 'capsid 표면의 작은 육각 기둥으로 표시해요.',
      simplification: 'hexon·penton 구분과 실제 수는 화면용으로 줄였어요.',
      evidence: 'observed',
      sourceIds: ['pdb-3j7v'],
    }),
    family('t7', [partTarget('genome'), layerTarget('genome')], {
      genericSummary: 'T7 머리 안에 조밀하게 포장되는 선형 이중가닥 DNA예요.',
      actualName: 'T7 linear dsDNA genome',
      role: '감염 시 짧은 꼬리와 ejection 단백질 경로를 통해 세포로 전달돼요.',
      location: 'capsid 내부',
      relationships: ['portal과 inner tube가 DNA 방출 축을 이뤄요.'],
      modelRepresentation: '머리 내부의 보라색 코일로 표시해요.',
      simplification: '실제 DNA 층상 포장과 ejection 단백질은 생략했어요.',
      evidence: 'observed',
      sourceIds: ['pdb-3j7v'],
    }),
    family('t7', [partTarget('portal')], {
      genericSummary: 'T7 머리의 고유 꼭짓점에서 DNA 포장·방출 축을 만드는 복합체예요.',
      actualName: 'T7 gp8 portal complex',
      role: '조립 중 DNA가 들어가고 감염 시 빠져나오는 머리 출구를 만들어요.',
      location: 'capsid와 짧은 꼬리 사이의 고유 꼭짓점',
      relationships: ['위쪽 DNA와 아래쪽 tail tube를 축 방향으로 이어줘요.'],
      modelRepresentation: 'capsid 아래의 짧은 금색 고리로 표시해요.',
      simplification: 'portal의 oligomeric 세부와 대칭 불일치는 생략해요.',
      evidence: 'observed',
      sourceIds: ['pdb-7ey7'],
    }),
    family('t7', [partTarget('inner-tube'), layerTarget('tail')], {
      genericSummary: 'T7의 짧은 비수축형 꼬리와 DNA 전달 관이에요.',
      actualName: 'T7 short tail tube complex',
      role: '숙주 표면 접촉 뒤 DNA 방출 통로를 정렬해요.',
      location: 'portal 아래의 짧은 축 구조',
      relationships: ['portal과 말단 섬유 사이에 놓여요.'],
      modelRepresentation: '짧은 중심 원통과 말단판으로 표시해요.',
      simplification: '여러 꼬리·ejection 단백질을 하나의 관형 그룹으로 줄였어요.',
      evidence: 'observed',
      sourceIds: ['pdb-7ey7'],
    }),
    family('t7', [partTarget('tail-fiber')], {
      genericSummary: 'T7 짧은 꼬리 둘레의 숙주 인식 섬유예요.',
      actualName: 'T7 gp17 tail fibers',
      role: '세균 표면 수용체를 탐색하고 짧은 꼬리를 숙주에 고정해요.',
      location: '짧은 꼬리 기부 둘레',
      relationships: ['tail tube와 함께 감염 시작점의 숙주 접촉 장치를 이뤄요.'],
      modelRepresentation: '꼬리 끝에서 여러 방향으로 꺾여 뻗는 가는 선으로 표시해요.',
      simplification: 'gp17의 마디와 receptor-binding tip 구조는 줄였어요.',
      evidence: 'observed',
      sourceIds: ['pdb-7ey7'],
    }),

    family('ms2', [partTarget('capsid'), layerTarget('capsid')], {
      genericSummary: 'MS2 RNA를 감싸는 작은 T=3 정이십면체 단백질 껍질이에요.',
      actualName: 'MS2 coat-protein T=3 capsid',
      role: 'RNA를 보호하고 한 자리의 maturation protein과 함께 감염성 입자를 만들어요.',
      location: '꼬리 없는 입자의 바깥 단백질 shell',
      relationships: [
        'capsomer 반복 가운데 한 자리만 maturation protein으로 치환돼요.',
      ],
      modelRepresentation: '작은 정이십면체 shell로 표시해요.',
      simplification: 'coat protein의 A/B/C 준등가 상태는 분리하지 않아요.',
      evidence: 'observed',
      sourceIds: ['pdb-5tc1'],
    }),
    family('ms2', [partTarget('capsomer')], {
      genericSummary: 'MS2 T=3 shell을 만드는 coat-protein dimer 반복이에요.',
      actualName: 'MS2 coat-protein dimers',
      role: 'RNA와 상호작용하며 반복 조립되어 capsid를 만들어요.',
      location: 'capsid 표면',
      relationships: [
        '대부분의 표면을 이루고 비대칭 maturation protein 자리와 접해요.',
      ],
      modelRepresentation: 'capsid 표면의 작은 반복 기둥으로 표시해요.',
      simplification: 'dimer의 접힘과 준등가 배열을 하나의 반복 모양으로 줄였어요.',
      evidence: 'observed',
      sourceIds: ['pdb-5tc1'],
    }),
    family('ms2', [partTarget('maturation-protein')], {
      genericSummary: 'MS2 capsid의 한 비대칭 자리를 차지하는 숙주 결합 단백질이에요.',
      actualName: 'MS2 maturation protein (A protein)',
      role: '숙주 pilus에 결합하고 RNA와 capsid를 연결해 감염을 시작해요.',
      location: 'T=3 capsid의 단 하나의 비대칭 자리',
      relationships: ['coat-protein shell을 깨는 고유 위치에서 RNA와 접촉해요.'],
      modelRepresentation: 'capsid 한쪽의 색이 다른 큰 패치로 표시해요.',
      simplification: 'A protein의 전체 비대칭 접촉면은 강조 패치로 줄였어요.',
      evidence: 'observed',
      sourceIds: ['pdb-5tc1'],
    }),
    family('ms2', [partTarget('genome'), layerTarget('genome')], {
      genericSummary: 'MS2 capsid 안에서 단백질과 접촉하며 접힌 양성가닥 RNA예요.',
      actualName: 'MS2 positive-sense ssRNA genome',
      role: '바이러스 단백질 번역과 복제에 필요한 유전정보를 담아요.',
      location: 'T=3 capsid 내부',
      relationships: ['coat protein과 maturation protein 양쪽에 접촉해요.'],
      modelRepresentation: 'capsid 안의 불규칙한 보라색 곡선으로 표시해요.',
      simplification: 'RNA의 실제 3차 접힘과 protein-binding stem-loop는 생략해요.',
      evidence: 'observed',
      sourceIds: ['pdb-5tc1'],
    }),

    family('tmv', [partTarget('capsid'), layerTarget('capsid')], {
      genericSummary: 'TMV coat protein이 나선형으로 조립된 단단한 막대 피복이에요.',
      actualName: 'TMV helical coat-protein capsid',
      role: 'RNA를 일정한 나선 경로에 고정하고 외부 환경에서 보호해요.',
      location: '막대형 입자의 바깥 단백질층',
      relationships: ['안쪽 RNA와 중심 채널을 둘러싸는 하나의 나선 shell이에요.'],
      modelRepresentation: '속이 빈 단단한 원통 shell로 표시해요.',
      simplification: '원자 표면과 실제 helical pitch는 반복 capsule 기하로 줄였어요.',
      evidence: 'observed',
      sourceIds: ['pdb-2tmv'],
    }),
    family('tmv', [partTarget('coat-protein')], {
      genericSummary: 'TMV 막대 shell을 이루는 동일 coat protein 반복이에요.',
      actualName: 'TMV coat protein subunits',
      role: 'RNA의 반복 결합 부위를 따라 나선형 capsid를 조립해요.',
      location: '중심 채널 둘레의 원통 표면',
      relationships: ['각 subunit이 이웃 단백질과 RNA 양쪽에 접촉해요.'],
      modelRepresentation: '원통 둘레의 작은 capsule 반복으로 표시해요.',
      simplification: 'subunit의 원자 접힘은 동일한 캡슐 모양으로 줄였어요.',
      evidence: 'observed',
      sourceIds: ['pdb-2tmv'],
    }),
    family('tmv', [partTarget('channel')], {
      genericSummary: 'TMV 나선 capsid 중심을 축 방향으로 관통하는 빈 공간이에요.',
      actualName: 'TMV central channel',
      role: '단백질이 둘러싼 나선 assembly의 중심축을 정의해요.',
      location: '막대형 입자의 중심축',
      relationships: ['RNA는 채널 안이 아니라 coat protein 안쪽 홈을 따라 놓여요.'],
      modelRepresentation: 'capsid 중앙의 길고 빈 원통으로 보여요.',
      simplification: '채널 벽의 원자 표면과 용매는 표현하지 않아요.',
      evidence: 'observed',
      sourceIds: ['pdb-2tmv'],
    }),
    family('tmv', [partTarget('genome'), layerTarget('genome')], {
      genericSummary: 'TMV coat protein 안쪽 홈을 따라 감기는 양성가닥 RNA예요.',
      actualName: 'TMV positive-sense ssRNA genome',
      role: '감염 뒤 번역과 복제에 사용되는 유전정보를 담아요.',
      location: 'coat-protein shell 안쪽, 중심 채널 바깥',
      relationships: ['반복 coat protein subunit마다 일정한 RNA 구간이 결합해요.'],
      modelRepresentation: '원통 안쪽을 따라 감기는 보라색 나선으로 표시해요.',
      simplification: 'RNA 서열과 국소 접힘은 균일한 나선으로 줄였어요.',
      evidence: 'observed',
      sourceIds: ['pdb-2tmv'],
    }),

    family('m13', [partTarget('capsid'), layerTarget('capsid')], {
      genericSummary: 'M13의 원형 ssDNA를 감싸는 매우 길고 가는 필라멘트 피복이에요.',
      actualName: 'M13 filamentous capsid',
      role: 'ssDNA를 축 방향으로 포장하고 감염·조립 말단 단백질을 지지해요.',
      location: '필라멘트 입자의 바깥 단백질 shell',
      relationships: [
        '주요 coat protein 몸체 양끝에 서로 다른 minor protein이 모여요.',
      ],
      modelRepresentation: '완만하게 휘는 가는 관형 shell로 표시해요.',
      simplification: '실제 길이를 크게 줄이고 helical symmetry를 단순화했어요.',
      evidence: 'observed',
      sourceIds: ['pdb-2mjz'],
    }),
    family('m13', [partTarget('coat-protein')], {
      genericSummary: 'M13 필라멘트 몸체 대부분을 이루는 주요 피복 단백질이에요.',
      actualName: 'M13 major coat protein pVIII',
      role: 'ssDNA를 둘러싸며 수천 개의 반복으로 긴 필라멘트를 만들어요.',
      location: '두 말단 사이의 긴 원통형 몸체',
      relationships: ['양끝의 pIII/pVI 및 pVII/pIX minor protein 복합체와 이어져요.'],
      modelRepresentation: '필라멘트 표면의 촘촘한 짧은 반복으로 표시해요.',
      simplification: 'pVIII의 실제 수와 helical packing은 크게 줄였어요.',
      evidence: 'observed',
      sourceIds: ['pdb-2mjz'],
    }),
    family('m13', [partTarget('terminal-protein')], {
      genericSummary:
        'M13 필라멘트 양끝에서 감염과 조립을 나눠 맡는 minor coat protein이에요.',
      actualName: 'M13 pIII/pVI and pVII/pIX terminal complexes',
      role: 'pIII가 숙주 pilus 인식에 관여하고 반대쪽 단백질군은 입자 조립 말단을 닫아요.',
      location: '긴 필라멘트의 양끝',
      relationships: ['pVIII 몸체와 원형 ssDNA의 끝 방향을 구분해요.'],
      modelRepresentation: '양끝의 색과 크기가 다른 짧은 마개로 표시해요.',
      simplification: '네 종류 minor protein을 두 개의 말단 기하로 합쳤어요.',
      evidence: 'family-supported',
      sourceIds: ['pdb-2mjz'],
    }),
    family('m13', [partTarget('genome'), layerTarget('genome')], {
      genericSummary: 'M13 필라멘트 안에서 길게 펴져 포장되는 원형 단일가닥 DNA예요.',
      actualName: 'M13 circular ssDNA genome',
      role: '숙주에 전달되어 복제형 DNA를 만들 유전정보를 담아요.',
      location: 'pVIII coat-protein shell의 중심축 안쪽',
      relationships: [
        '주요 coat protein과 정전기적으로 결합한 채 필라멘트 길이를 따라가요.',
      ],
      modelRepresentation: '필라멘트 중심을 따라가는 한 줄의 보라색 곡선으로 표시해요.',
      simplification: '원형 연결과 실제 DNA–protein 접촉은 축 방향 선으로 줄였어요.',
      evidence: 'family-supported',
      sourceIds: ['pdb-2mjz'],
    }),

    family('vsv', [partTarget('envelope'), layerTarget('envelope')], {
      genericSummary: 'VSV의 총알형 입자 바깥을 둘러싸는 숙주 유래 지질막이에요.',
      actualName: 'VSV lipid envelope',
      role: 'G glycoprotein을 지지하고 M matrix와 나선형 nucleocapsid를 감싸요.',
      location: '총알형 입자의 최외곽',
      relationships: ['바깥 G와 안쪽 M layer 사이에 놓여요.'],
      modelRepresentation:
        '둥근 앞쪽과 평평한 뒤쪽을 가진 반투명 총알 shell로 표시해요.',
      simplification: '막의 지질 조성과 국소 곡률은 균일한 표면으로 줄였어요.',
      evidence: 'observed',
      sourceIds: ['emd-26603'],
    }),
    family('vsv', [partTarget('spike'), layerTarget('surface-protein')], {
      genericSummary: 'VSV가 숙주 세포 부착과 막 융합에 사용하는 표면 당단백질이에요.',
      actualName: 'VSV glycoprotein G',
      role: '숙주 세포 진입과 낮은 pH에서의 막 융합을 매개해요.',
      location: '총알형 지질 외피 표면',
      relationships: ['외피를 관통하고 안쪽 M layer보다 바깥으로 돌출해요.'],
      modelRepresentation: '총알 표면의 짧은 반복 돌기로 표시해요.',
      simplification: 'G trimer의 형태 전환과 당쇄는 생략했어요.',
      evidence: 'observed',
      sourceIds: ['emd-26603'],
    }),
    family('vsv', [partTarget('matrix'), layerTarget('matrix')], {
      genericSummary: 'VSV 외피와 nucleocapsid 사이를 잇는 matrix 단백질층이에요.',
      actualName: 'VSV matrix protein M layer',
      role: '총알형 입자 조립과 출아를 돕고 내부 RNP를 막에 연결해요.',
      location: '지질 외피 바로 안쪽',
      relationships: ['바깥 envelope와 안쪽 N–RNA helix 사이에 놓여요.'],
      modelRepresentation: '외피보다 작은 총알형 연속 shell로 표시해요.',
      simplification: '개별 M 단백질 배열은 균일한 층으로 줄였어요.',
      evidence: 'observed',
      sourceIds: ['emd-26603'],
    }),
    family('vsv', [partTarget('nucleocapsid'), layerTarget('nucleocapsid')], {
      genericSummary:
        'VSV N 단백질이 음성가닥 RNA를 감싼 나선형 ribonucleoprotein이에요.',
      actualName: 'VSV N protein–RNA nucleocapsid',
      role: 'RNA를 보호하고 polymerase가 전사·복제할 template을 만들어요.',
      location: 'M matrix 안쪽의 총알형 중심부',
      relationships: [
        'RNA와 N 단백질이 함께 감겨 있고 L·P polymerase complex와 기능적으로 연결돼요.',
      ],
      modelRepresentation: '총알 내부를 채우는 방향성 있는 굵은 나선으로 표시해요.',
      simplification: 'N subunit과 L·P complex는 별도 원자 형상으로 분리하지 않아요.',
      evidence: 'observed',
      sourceIds: ['emd-26603'],
    }),
    family('vsv', [partTarget('genome'), layerTarget('genome')], {
      genericSummary: 'VSV N 단백질에 둘러싸여 포장되는 비분절 음성가닥 RNA예요.',
      actualName: 'VSV negative-sense ssRNA genome',
      role: '바이러스 단백질 전사와 새 RNA 복제의 template을 제공해요.',
      location: '나선형 nucleocapsid 내부',
      relationships: ['맨 RNA가 아니라 N protein–RNA complex의 일부로 존재해요.'],
      modelRepresentation: 'nucleocapsid 나선 중심의 보라색 경로로 표시해요.',
      simplification: 'RNA 서열과 N 결합 간격은 연속 곡선으로 줄였어요.',
      evidence: 'observed',
      sourceIds: ['emd-26603'],
    }),

    family('vaccinia', [partTarget('envelope'), layerTarget('membrane')], {
      genericSummary:
        'Vaccinia mature virion(MV)의 벽돌형 입자를 감싸는 lipoprotein membrane이에요.',
      actualName: 'Vaccinia MV outer lipoprotein membrane',
      role: '표면 entry protein을 지지하고 내부 core와 lateral body를 감싸요.',
      location: '성숙 MV 입자의 가장 바깥쪽',
      relationships: ['안쪽의 core wall과 두 lateral body를 하나의 입자로 둘러싸요.'],
      modelRepresentation:
        '모서리가 둥근 반투명 벽돌형 외곽과 얕은 표면 능선으로 표시해요.',
      simplification: 'MV 막층의 세부 수와 표면 단백질은 하나의 외곽 구조로 합쳤어요.',
      evidence: 'observed',
      sourceIds: ['ictv-pox', 'pnas-vaccinia'],
    }),
    family('vaccinia', [partTarget('core-wall'), layerTarget('core-wall')], {
      genericSummary: 'Vaccinia 유전체를 감싸는 아령 모양 core의 단백질성 벽이에요.',
      actualName: 'Vaccinia dumbbell-shaped core wall',
      role: 'dsDNA와 초기 전사 장치를 보호하고 세포 진입 뒤 단계적으로 해체돼요.',
      location: '벽돌형 막 안쪽의 중앙',
      relationships: ['양옆 lateral body 사이에 놓이며 내부에 dsDNA를 담아요.'],
      modelRepresentation: '가운데가 좁은 불투명 아령형 shell로 표시해요.',
      simplification:
        'core wall의 palisade 표면과 내부 효소층은 저해상도 shell로 줄였어요.',
      evidence: 'observed',
      sourceIds: ['pnas-vaccinia'],
    }),
    family('vaccinia', [partTarget('lateral-body'), layerTarget('lateral-body')], {
      genericSummary:
        'Vaccinia core 양옆에 놓여 감염 초기에 전달되는 단백질을 담는 구조예요.',
      actualName: 'Vaccinia paired lateral bodies',
      role: '숙주 세포 안으로 방출되는 효소와 조절 단백질의 저장 영역으로 기능해요.',
      location: 'core wall 양옆과 바깥 막 사이',
      relationships: ['중앙 core를 좌우에서 감싸며 membrane 안쪽에 놓여요.'],
      modelRepresentation: 'core 양옆의 서로 분리된 두 타원체로 표시해요.',
      simplification: '단백질 조성과 비대칭 밀도는 균일한 두 덩어리로 줄였어요.',
      evidence: 'observed',
      sourceIds: ['pnas-vaccinia'],
    }),
    family('vaccinia', [partTarget('genome'), layerTarget('genome')], {
      genericSummary: 'Vaccinia core 안에 포장되는 선형 이중가닥 DNA예요.',
      actualName: 'Vaccinia linear dsDNA genome',
      role: '세포질에서 복제·발현되는 큰 poxvirus 유전정보를 담아요.',
      location: '아령 모양 core wall 내부',
      relationships: ['초기 전사효소와 함께 core 안에 들어 있어요.'],
      modelRepresentation: 'core 내부의 굵은 보라색 코일로 표시해요.',
      simplification: 'DNA 말단 구조와 포장 단백질·효소는 단일 코일로 줄였어요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-pox', 'pnas-vaccinia'],
    }),

    family('hbv', [partTarget('envelope'), layerTarget('envelope')], {
      genericSummary:
        '감염성 HBV Dane particle의 바깥을 둘러싸는 숙주 유래 지질막이에요.',
      actualName: 'HBV lipid envelope',
      role: 'L·M·S surface protein을 지지하고 nucleocapsid를 감싸요.',
      location: 'Dane particle의 최외곽',
      relationships: ['표면 HBs protein과 안쪽 HBc capsid 사이에 놓여요.'],
      modelRepresentation: '반투명한 작은 구형 막으로 표시해요.',
      simplification:
        '지질 조성과 세 종류 surface protein의 분포는 균일한 막으로 줄였어요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-hepadnaviridae'],
    }),
    family('hbv', [partTarget('spike'), layerTarget('surface-protein')], {
      genericSummary: 'HBV 외피에 박힌 large·middle·small surface protein이에요.',
      actualName: 'HBV surface proteins L-HBs, M-HBs and S-HBs',
      role: 'L protein의 preS1 영역이 숙주 수용체 결합에 핵심적으로 관여하고 외피 조립에도 참여해요.',
      location: '지질 외피 표면과 막 내부',
      relationships: ['같은 S 영역을 공유하는 세 단백질이 envelope를 구성해요.'],
      modelRepresentation: '외피 표면의 짧고 조밀한 돌기로 함께 표시해요.',
      simplification:
        'L/M/S의 비율·방향과 preS domain은 개별 형상으로 구분하지 않아요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-hepadnaviridae'],
    }),
    family('hbv', [partTarget('core-capsid'), layerTarget('core-capsid')], {
      genericSummary:
        'HBV DNA와 polymerase를 감싸는 T=3/T=4 icosahedral nucleocapsid예요.',
      actualName: 'HBV core protein (HBc) capsid',
      role: '역전사 중인 핵산과 polymerase를 보호하고 세포 내 운반에 관여해요.',
      location: '지질 외피 안쪽',
      relationships: [
        'capsomer 반복이 core shell을 만들고 내부 genome·polymerase를 둘러싸요.',
      ],
      modelRepresentation: '외피 안쪽의 작은 정이십면체 shell로 표시해요.',
      simplification: 'T=3/T=4 다양성 가운데 하나의 균일한 core shell만 보여줘요.',
      evidence: 'observed',
      sourceIds: ['pdb-6htx'],
    }),
    family('hbv', [partTarget('capsomer')], {
      genericSummary: 'HBV core shell을 이루는 HBc dimer의 반복 단위예요.',
      actualName: 'HBV core protein (HBc) dimers',
      role: '서로 조립되어 icosahedral nucleocapsid를 만들어요.',
      location: 'HBV core capsid 표면',
      relationships: ['인접 dimer와 결합해 genome·polymerase를 감싸는 shell을 이뤄요.'],
      modelRepresentation: 'core 표면의 작은 반복 기둥으로 표시해요.',
      simplification: 'HBc dimer spike와 flexible tail은 단순 반복 단위로 줄였어요.',
      evidence: 'observed',
      sourceIds: ['pdb-6htx'],
    }),
    family('hbv', [partTarget('genome'), layerTarget('genome')], {
      genericSummary:
        '성숙 HBV 입자에 polymerase와 함께 들어 있는 relaxed circular 부분 이중가닥 DNA예요.',
      actualName: 'Relaxed circular partially double-stranded DNA genome',
      role: '핵으로 전달되어 cccDNA 형성의 기질이 되는 유전정보를 담아요.',
      location: 'HBc nucleocapsid 내부',
      relationships: [
        'viral polymerase가 DNA 한 가닥 말단에 결합하지만 현재 모델에는 별도 형상이 없어요.',
      ],
      modelRepresentation: 'core 안쪽의 일부가 열린 보라색 이중 곡선으로 표시해요.',
      simplification: '가닥 길이 차이, polymerase와 RNA primer는 생략했어요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-hepadnaviridae'],
    }),

    family('alphavirus', [partTarget('envelope'), layerTarget('envelope')], {
      genericSummary:
        'Alphavirus의 정렬된 glycoprotein lattice 아래에 있는 지질 외피예요.',
      actualName: 'Alphavirus lipid envelope',
      role: 'E1/E2 spike를 지지하고 내부 icosahedral nucleocapsid를 감싸요.',
      location: '입자의 바깥 막층',
      relationships: ['바깥 E1/E2 lattice와 안쪽 capsid-protein core 사이에 놓여요.'],
      modelRepresentation: '정이십면체 성격이 드러나는 반투명 구형 막으로 표시해요.',
      simplification: '지질 분자와 membrane curvature의 미세 차이는 생략해요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-togaviridae'],
    }),
    family('alphavirus', [partTarget('spike'), layerTarget('surface-protein')], {
      genericSummary:
        'Alphavirus 표면에서 숙주 인식과 막 융합을 나눠 맡는 glycoprotein complex예요.',
      actualName: 'E1–E2 glycoprotein spikes',
      role: 'E2가 수용체 상호작용에, E1이 낮은 pH의 막 융합에 주로 관여해요.',
      location: '지질 외피 표면의 정렬된 lattice',
      relationships: [
        'E1/E2가 외피를 관통하고 안쪽 capsid protein과 방사형으로 정렬돼요.',
      ],
      modelRepresentation: '외피 표면의 조밀한 삼엽형 돌기로 반복해 표시해요.',
      simplification:
        'E1/E2 heterodimer와 trimeric spike의 원자 구조는 한 돌기 모양으로 줄였어요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-togaviridae'],
    }),
    family(
      'alphavirus',
      [partTarget('nucleocapsid'), partTarget('capsomer'), layerTarget('nucleocapsid')],
      {
        genericSummary:
          'Alphavirus capsid protein이 RNA를 감싸 만든 icosahedral nucleocapsid예요.',
        actualName: 'Capsid-protein icosahedral nucleocapsid',
        role: '양성가닥 RNA를 포장하고 외피 glycoprotein lattice와 정렬된 내부 core를 만들어요.',
        location: '지질 외피 안쪽의 중심',
        relationships: ['바깥 E1/E2 lattice와 막을 사이에 두고 방사형으로 대응해요.'],
        modelRepresentation: '작은 정이십면체 shell과 반복 capsomer로 표시해요.',
        simplification:
          'capsid protein–RNA 접촉과 실제 T=4 격자는 단순 shell로 줄였어요.',
        evidence: 'family-supported',
        sourceIds: ['pdb-6imm', 'ictv-togaviridae'],
      },
    ),
    family('alphavirus', [partTarget('genome'), layerTarget('genome')], {
      genericSummary: 'Alphavirus nucleocapsid 안에 포장되는 양성가닥 RNA예요.',
      actualName: 'Alphavirus positive-sense ssRNA genome',
      role: '감염 뒤 바로 번역되고 새 genome과 subgenomic RNA 생성의 template이 돼요.',
      location: 'capsid-protein nucleocapsid 내부',
      relationships: ['capsid protein과 결합해 icosahedral core 안에 포장돼요.'],
      modelRepresentation: 'nucleocapsid 안쪽의 보라색 코일로 표시해요.',
      simplification: 'RNA 접힘과 capsid 결합 신호는 단일 곡선으로 줄였어요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-togaviridae'],
    }),

    family('cystovirus', [partTarget('envelope'), layerTarget('envelope')], {
      genericSummary: 'Phi6 입자 바깥을 둘러싸는 숙주 유래 지질 외피예요.',
      actualName: 'Phi6 lipid envelope with membrane protein P9',
      role: '숙주 인식 단백질을 지지하고 내부 nucleocapsid를 감싸요.',
      location: '입자의 가장 바깥쪽',
      relationships: ['바깥 P3 spike와 안쪽 P8 shell 사이에 놓여요.'],
      modelRepresentation: '반투명한 구형 막으로 표시해요.',
      simplification: 'P9와 기타 membrane protein은 개별 형상으로 구분하지 않아요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-cystoviridae'],
    }),
    family('cystovirus', [partTarget('spike'), layerTarget('surface-protein')], {
      genericSummary: 'Phi6가 세균 표면을 인식하는 외피 부착 단백질이에요.',
      actualName: 'Phi6 host-attachment protein P3',
      role: '숙주 수용체를 인식해 외피 입자의 부착을 시작해요.',
      location: '지질 외피 표면',
      relationships: ['외피에 결합하고 내부 capsid 층보다 바깥으로 돌출해요.'],
      modelRepresentation: '외피 표면의 드문 길쭉한 돌기로 표시해요.',
      simplification: 'P3의 유연성과 결합 복합체는 단일 돌기로 줄였어요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-cystoviridae'],
    }),
    family('cystovirus', [partTarget('outer-capsid'), layerTarget('outer-capsid')], {
      genericSummary: 'Phi6 polymerase core를 감싸는 바깥쪽 nucleocapsid shell이에요.',
      actualName: 'Phi6 P8 nucleocapsid shell',
      role: '내부 P1 core를 보호하고 감염 과정의 단계적 uncoating에 참여해요.',
      location: '지질 외피 안쪽, P1 core 바깥',
      relationships: ['바깥 envelope와 안쪽 polymerase complex 사이에 놓여요.'],
      modelRepresentation: '외피 안쪽의 얇은 정이십면체 shell로 표시해요.',
      simplification: 'P8 trimer lattice는 균일한 다면체 표면으로 줄였어요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-cystoviridae'],
    }),
    family('cystovirus', [partTarget('core-capsid'), layerTarget('core-capsid')], {
      genericSummary: 'Phi6 dsRNA와 polymerase를 담는 가장 안쪽 단백질 core예요.',
      actualName: 'Phi6 P1 polymerase complex shell',
      role: '세 RNA 분절을 포장하고 내부에서 전사·복제를 수행하는 반응 용기를 만들어요.',
      location: 'P8 shell 안쪽의 중심',
      relationships: ['P8 layer에 둘러싸이고 내부 dsRNA·polymerase와 연결돼요.'],
      modelRepresentation: '가장 안쪽의 작은 정이십면체 shell로 표시해요.',
      simplification:
        'P1 lattice와 P2 polymerase·P4 packaging ATPase는 하나의 core로 합쳤어요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-cystoviridae'],
    }),
    family('cystovirus', [partTarget('genome'), layerTarget('genome')], {
      genericSummary: 'Phi6 polymerase core 안에 포장된 세 분절의 이중가닥 RNA예요.',
      actualName: 'Phi6 L, M and S dsRNA genome segments',
      role: '바이러스 단백질 발현과 새 RNA 합성에 필요한 유전정보를 나눠 담아요.',
      location: 'P1 polymerase complex shell 내부',
      relationships: [
        'P2 polymerase가 core 안에서 각 dsRNA를 전사하지만 별도 형상은 없어요.',
      ],
      modelRepresentation: 'core 안의 세 개 보라색 곡선 묶음으로 표시해요.',
      simplification:
        '분절별 길이와 이중나선·polymerase 배치는 단순 곡선으로 줄였어요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-cystoviridae'],
    }),

    family('geminate-capsid', [partTarget('capsid'), layerTarget('capsid')], {
      genericSummary:
        '두 불완전한 정이십면체가 맞붙은 geminate 식물바이러스 capsid예요.',
      actualName: 'Geminivirus coat-protein twin capsid',
      role: '원형 ssDNA를 보호하고 곤충 매개체와 식물 숙주에서 입자 안정성을 제공해요.',
      location: '쌍둥이형 입자의 바깥 단백질 shell',
      relationships: ['두 capsid 절반이 중앙 interface에서 맞붙어요.'],
      modelRepresentation: '서로 겹친 두 개의 길쭉한 다면체 shell로 표시해요.',
      simplification: 'coat protein의 실제 T=1 유사 배열은 두 shell로 줄였어요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-geminiviridae'],
    }),
    family('geminate-capsid', [partTarget('capsomer')], {
      genericSummary:
        'geminate capsid 표면을 이루는 동일 coat-protein subunit 반복이에요.',
      actualName: 'Geminivirus coat protein (CP) subunits',
      role: '두 capsid 절반을 조립하고 ssDNA 포장에 관여해요.',
      location: '쌍둥이형 capsid 표면',
      relationships: ['인접 subunit 및 중앙 interface의 subunit과 접촉해요.'],
      modelRepresentation: '두 다면체 표면의 작은 반복 단위로 표시해요.',
      simplification: 'subunit의 원자 접힘과 실제 수는 반복 기하로 줄였어요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-geminiviridae'],
    }),
    family('geminate-capsid', [partTarget('geminate-bridge')], {
      genericSummary:
        '두 capsid 절반이 맞닿아 하나의 geminate 입자를 이루는 접촉 영역이에요.',
      actualName: 'Geminate capsid interface',
      role: '두 incomplete T=1 shell을 하나의 안정한 쌍둥이형 입자로 연결해요.',
      location: '두 다면체의 중앙 접합부',
      relationships: [
        '별도 단백질 다리가 아니라 coat-protein shell 사이의 interface예요.',
      ],
      modelRepresentation: '두 shell 사이의 좁은 연결 띠로 강조해요.',
      simplification: '실제 subunit 접촉을 독립된 bridge 부품처럼 보이게 단순화했어요.',
      evidence: 'conceptual',
      sourceIds: ['ictv-geminiviridae'],
    }),
    family('geminate-capsid', [partTarget('genome'), layerTarget('genome')], {
      genericSummary: 'geminate capsid 안에 포장되는 원형 단일가닥 DNA예요.',
      actualName: 'Circular ssDNA genome',
      role: '식물 세포핵에서 복제될 바이러스 유전정보를 담아요.',
      location: '두 capsid 절반이 만드는 내부 공간',
      relationships: ['coat protein과 결합한 상태로 twin capsid 안에 들어 있어요.'],
      modelRepresentation: '두 lobe 사이를 오가는 보라색 고리형 곡선으로 표시해요.',
      simplification: 'DNA 원형 연결과 단백질 결합 상태는 단순 곡선으로 줄였어요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-geminiviridae'],
    }),

    family('archaeal-rod', [partTarget('capsid'), layerTarget('capsid')], {
      genericSummary: 'SIRV2 DNA를 감싸는 단단한 막대형 helical capsid예요.',
      actualName: 'SIRV2 helical rod-shaped capsid',
      role: '선형 dsDNA를 고온·산성 환경에서 안정하게 보호해요.',
      location: '두 말단 섬유 사이의 긴 막대 몸체',
      relationships: ['양끝 terminal fiber와 내부 DNA를 하나의 축으로 연결해요.'],
      modelRepresentation: '잘 휘지 않는 속이 찬 긴 원통으로 표시해요.',
      simplification: '실제 helical symmetry와 표면 홈은 균일한 rod로 줄였어요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-rudiviridae'],
    }),
    family('archaeal-rod', [partTarget('coat-protein')], {
      genericSummary:
        'SIRV2 dsDNA 둘레에 반복되어 막대형 capsid를 만드는 주요 단백질이에요.',
      actualName: 'SIRV2 major capsid protein dimers',
      role: 'DNA와 결합해 연속적인 helical nucleoprotein filament를 만들어요.',
      location: '막대 몸체 전체 표면과 내부 DNA 둘레',
      relationships: ['인접 dimer와 DNA가 함께 단단한 rod 구조를 이뤄요.'],
      modelRepresentation: '원통 표면의 짧은 반복 띠로 표시해요.',
      simplification: 'dimer의 구조와 DNA wrapping은 동일 반복 모양으로 줄였어요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-rudiviridae'],
    }),
    family('archaeal-rod', [partTarget('terminal-tail'), layerTarget('tail')], {
      genericSummary: 'SIRV2 막대 양끝에서 숙주 표면과 상호작용하는 세 갈래 섬유예요.',
      actualName: 'SIRV2 terminal fiber complexes',
      role: '숙주 세포 표면 부착의 방향성 있는 말단 장치로 기능해요.',
      location: '막대형 capsid의 양끝',
      relationships: ['중앙 coat-protein rod와 축 방향으로 이어져요.'],
      modelRepresentation: '각 끝에서 세 방향으로 뻗는 분절 선으로 표시해요.',
      simplification: '말단 단백질의 분자 조성과 유연성은 세 갈래 선으로 줄였어요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-rudiviridae'],
    }),
    family('archaeal-rod', [partTarget('genome'), layerTarget('genome')], {
      genericSummary:
        'SIRV2 coat protein과 결합해 막대 안에 포장되는 선형 이중가닥 DNA예요.',
      actualName: 'SIRV2 linear dsDNA genome',
      role: '고세균 숙주에서 복제될 바이러스 유전정보를 담아요.',
      location: 'helical rod-shaped capsid의 중심축',
      relationships: [
        'major capsid protein dimer에 둘러싸여 nucleoprotein filament를 이뤄요.',
      ],
      modelRepresentation: '막대 중심을 따라가는 보라색 직선으로 표시해요.',
      simplification:
        'DNA의 A-form 유사 배치와 protein contact는 단일 선으로 줄였어요.',
      evidence: 'family-supported',
      sourceIds: ['ictv-rudiviridae'],
    }),
  ] as const;
