import type { ModelBuilderId } from '../types';
import { EXPANDED_FAMILY_STRUCTURE_EXPLANATIONS } from './expandedFamilies';
import {
  layerTarget,
  partTarget,
  type FamilyExplanationRegistration,
  type StructureExplanationContent,
  type StructureExplanationTarget,
} from './types';

const family = (
  modelBuilder: ModelBuilderId,
  targets: readonly StructureExplanationTarget[],
  explanation: StructureExplanationContent,
): FamilyExplanationRegistration => ({ modelBuilder, targets, explanation });

export const FAMILY_STRUCTURE_EXPLANATIONS: readonly FamilyExplanationRegistration[] = [
  family('coronavirus', [partTarget('envelope'), layerTarget('envelope')], {
    genericSummary: '숙주 세포에서 유래한 지질막이 입자 바깥을 둘러싸요.',
    actualName: '코로나바이러스 지질 외피',
    role: '막 단백질을 지지하고 내부 RNA-단백질 복합체를 감싸요.',
    location: '입자의 가장 바깥쪽 막층',
    relationships: ['표면의 S 단백질과 막 안쪽의 M 단백질층 사이에 놓여요.'],
    modelRepresentation: '반투명한 구형 지질막으로 단순화해 표시해요.',
    simplification: '개별 지질과 막 단백질은 원자 수준으로 분리하지 않아요.',
    evidence: 'family-supported',
    sourceIds: ['ictv-coronaviridae'],
  }),
  family('coronavirus', [partTarget('spike'), layerTarget('surface-protein')], {
    genericSummary:
      '코로나바이러스 외피에는 S·M·E 구조 단백질이 서로 다른 양과 형태로 있어요.',
    actualName: 'Spike (S), membrane (M), and envelope (E) proteins',
    role: 'S는 수용체 결합과 막 융합, M은 조립과 형태 유지, E는 이온통로와 입자 형성에 관여해요.',
    location: '지질 외피 바깥 표면',
    relationships: [
      '세 단백질은 같은 외피에 박히며 M은 별도의 연속 matrix 선택 영역으로도 표현돼요.',
    ],
    modelRepresentation:
      'S는 왕관형, M은 짧은 돌기, E는 드문 channel 표식으로 구분해 표시해요.',
    simplification:
      '세 성분을 한 선택 그룹으로 묶으며 원자 구조·당쇄·실제 조성비는 재현하지 않아요.',
    evidence: 'family-supported',
    sourceIds: ['ictv-coronaviridae'],
  }),
  family('coronavirus', [partTarget('matrix'), layerTarget('matrix')], {
    genericSummary: '코로나바이러스 외피의 형태와 조립을 지지하는 막 단백질이에요.',
    actualName: 'Membrane protein (M)',
    role: '바이러스 조립과 출아에서 중심적인 막 골격 역할을 해요.',
    location: '지질 외피에 박힌 막 단백질층',
    relationships: ['외피와 내부 nucleocapsid 사이의 구조 관계를 이어줘요.'],
    modelRepresentation: '외피 안쪽의 연속된 얇은 shell로 표시해요.',
    simplification: '개별 M 단백질의 배열과 막 관통 형태는 생략해요.',
    evidence: 'family-supported',
    sourceIds: ['ictv-coronaviridae'],
  }),
  family('coronavirus', [partTarget('nucleocapsid'), layerTarget('nucleocapsid')], {
    genericSummary: '양성가닥 RNA와 nucleocapsid 단백질이 이루는 내부 복합체예요.',
    actualName: 'Coronavirus N protein–RNA nucleocapsid',
    role: 'RNA 유전체를 포장하고 복제·전사에 필요한 형태로 유지해요.',
    location: '외피와 M 단백질층 안쪽',
    relationships: [
      'RNA는 nucleocapsid 단백질과 결합한 상태로 입자 내부에 들어 있어요.',
    ],
    modelRepresentation: '내부의 굽은 보라색 RNP 가닥으로 함께 표시해요.',
    simplification: 'RNA와 단백질을 별도 원자 구조로 나누지 않아요.',
    evidence: 'family-supported',
    sourceIds: ['ictv-coronaviridae'],
  }),
  family('coronavirus', [partTarget('genome'), layerTarget('genome')], {
    genericSummary: '코로나바이러스 입자 안에 포장되는 단일 양성가닥 RNA예요.',
    actualName: 'Coronavirus positive-sense ssRNA genome',
    role: '감염 뒤 번역과 복제·전사에 사용되는 바이러스 유전정보를 담아요.',
    location: 'M 단백질층 안쪽에서 N 단백질과 결합한 상태',
    relationships: ['맨 RNA가 아니라 N protein–RNA nucleocapsid의 일부로 존재해요.'],
    modelRepresentation: 'nucleocapsid와 같은 내부 보라색 RNP 곡선으로 표시해요.',
    simplification: 'RNA 서열·접힘과 N 단백질 결합 위치는 별도로 그리지 않아요.',
    evidence: 'family-supported',
    sourceIds: ['ictv-coronaviridae'],
  }),
  family('filovirus', [partTarget('envelope'), layerTarget('envelope')], {
    genericSummary: '필라멘트 입자의 가장 바깥을 둘러싸는 숙주 유래 지질막이에요.',
    actualName: 'Filovirus lipid envelope',
    role: '표면 GP를 지지하고 matrix와 nucleocapsid를 감싸요.',
    location: '긴 필라멘트 몸체의 외곽',
    relationships: ['표면 GP와 안쪽 VP40 matrix 사이에 놓여요.'],
    modelRepresentation: '굽은 관 형태의 외곽 막으로 표시해요.',
    simplification: '막의 미세 조성과 실제 입자의 다양한 굽힘은 고정하지 않아요.',
    evidence: 'family-supported',
    sourceIds: ['ictv-orthoebolavirus'],
  }),
  family('filovirus', [partTarget('spike'), layerTarget('surface-protein')], {
    genericSummary: '필로바이러스 외피 표면의 당단백질 돌기예요.',
    actualName: 'Filovirus glycoprotein (GP)',
    role: '숙주 세포 부착과 막 융합을 매개해요.',
    location: '지질 외피 표면',
    relationships: ['외피를 관통해 바깥으로 돌출하고 VP40 matrix보다 바깥에 있어요.'],
    modelRepresentation: '필라멘트 표면에 반복되는 짧은 돌기로 표시해요.',
    simplification: 'GP 삼량체와 당쇄의 원자 구조는 생략해요.',
    evidence: 'family-supported',
    sourceIds: ['ictv-orthoebolavirus'],
  }),
  family('filovirus', [partTarget('matrix'), layerTarget('matrix')], {
    genericSummary: '외피 안쪽을 따라 입자의 형태와 조립을 지지하는 단백질층이에요.',
    actualName: 'VP40 matrix layer',
    role: '입자 조립과 출아를 주도하고 외피와 nucleocapsid의 배치를 연결해요.',
    location: '지질 외피 바로 안쪽',
    relationships: ['바깥 외피와 안쪽 나선형 nucleocapsid 사이에 놓여요.'],
    modelRepresentation: '외피보다 가는 안쪽 관형 shell로 표시해요.',
    simplification: 'VP40의 개별 배열과 막 결합 상태는 연속층으로 줄였어요.',
    evidence: 'family-supported',
    sourceIds: ['ictv-orthoebolavirus'],
  }),
  family('filovirus', [partTarget('nucleocapsid'), layerTarget('nucleocapsid')], {
    genericSummary: '음성가닥 RNA와 바이러스 단백질이 이루는 나선형 내부 복합체예요.',
    actualName: 'Filovirus helical nucleocapsid',
    role: 'RNA 유전체를 포장하고 복제·전사를 위한 ribonucleoprotein 틀을 만들어요.',
    location: 'VP40 matrix 안쪽의 필라멘트 중심부',
    relationships: ['RNA는 nucleoprotein과 결합해 나선형 nucleocapsid의 일부가 돼요.'],
    modelRepresentation: '몸체 중심선을 따라 감기는 단일 보라색 나선으로 표시해요.',
    simplification: '구성 단백질과 RNA를 각각 분리하지 않은 계열 수준 표현이에요.',
    evidence: 'family-supported',
    sourceIds: ['ictv-orthoebolavirus'],
  }),
  family('filovirus', [partTarget('genome'), layerTarget('genome')], {
    genericSummary:
      '필로바이러스 nucleoprotein에 감싸여 포장되는 비분절 음성가닥 RNA예요.',
    actualName: 'Filovirus negative-sense ssRNA genome',
    role: 'viral polymerase가 전사·복제할 유전정보 template을 제공해요.',
    location: 'VP40 matrix 안쪽의 나선형 nucleocapsid 내부',
    relationships: ['RNA는 NP에 결합하며 L·VP35 등과 기능적 RNP를 이뤄요.'],
    modelRepresentation: 'nucleocapsid와 같은 중심 보라색 나선 경로로 표시해요.',
    simplification: 'RNA와 NP·polymerase의 개별 구조는 하나의 나선으로 줄였어요.',
    evidence: 'family-supported',
    sourceIds: ['ictv-orthoebolavirus'],
  }),
  family('lentivirus', [partTarget('envelope'), layerTarget('envelope')], {
    genericSummary: '숙주 세포막에서 유래해 성숙 입자를 둘러싸는 지질 외피예요.',
    actualName: 'Lentivirus lipid envelope',
    role: 'Env를 지지하고 matrix와 capsid를 감싸요.',
    location: '성숙 입자의 가장 바깥쪽',
    relationships: ['표면 Env와 안쪽 matrix 사이에 놓여요.'],
    modelRepresentation: '반투명한 구형 지질막으로 표시해요.',
    simplification: '지질 조성과 막 단백질 분포는 재현하지 않아요.',
    evidence: 'family-supported',
    sourceIds: ['ictv-retroviridae'],
  }),
  family('lentivirus', [partTarget('spike'), layerTarget('surface-protein')], {
    genericSummary:
      '렌티바이러스가 숙주 세포를 인식하고 융합할 때 쓰는 외피 당단백질이에요.',
    actualName: 'Envelope glycoprotein (Env)',
    role: '수용체 결합과 바이러스·세포막 융합을 매개해요.',
    location: '지질 외피 표면',
    relationships: ['외피에 박혀 matrix와 capsid보다 바깥으로 돌출해요.'],
    modelRepresentation: '외피 표면의 드문 club-shaped 돌기로 표시해요.',
    simplification: '삼량체 구조와 당쇄를 단순화하고 수량을 줄였어요.',
    evidence: 'family-supported',
    sourceIds: ['ictv-retroviridae'],
  }),
  family('lentivirus', [partTarget('matrix'), layerTarget('matrix')], {
    genericSummary:
      '외피 안쪽을 따라 입자 조립과 형태를 지지하는 matrix 단백질층이에요.',
    actualName: 'Lentivirus matrix layer',
    role: '외피와 내부 capsid 사이를 조직하고 조립·출아에 관여해요.',
    location: '지질 외피 바로 안쪽',
    relationships: ['바깥 외피와 안쪽 capsid 사이에 놓여요.'],
    modelRepresentation: '외피 안쪽의 얇은 연속 shell로 표시해요.',
    simplification: '개별 단백질 격자를 연속 표면으로 줄였어요.',
    evidence: 'family-supported',
    sourceIds: ['ictv-retroviridae'],
  }),
  family('lentivirus', [partTarget('capsid'), layerTarget('capsid')], {
    genericSummary: '성숙 렌티바이러스의 유전체와 효소를 감싸는 내부 단백질 코어예요.',
    actualName: 'Mature lentivirus capsid',
    role: '바이러스 RNA와 효소를 보호하고 감염 초기의 uncoating을 조절해요.',
    location: 'matrix 안쪽',
    relationships: ['matrix와 분리된 내부 코어이며 RNA 유전체를 둘러싸요.'],
    modelRepresentation: '입자 안쪽의 비대칭 원뿔형 shell로 표시해요.',
    simplification: 'capsid 단백질 격자와 내부 효소는 생략해요.',
    evidence: 'family-supported',
    sourceIds: ['ictv-retroviridae', 'pdb-3j3q'],
  }),
  family('lentivirus', [partTarget('genome'), layerTarget('genome')], {
    genericSummary: '성숙 입자 안에 두 분자가 함께 포장되는 양성가닥 RNA 유전체예요.',
    actualName: 'Paired lentivirus genomic RNA',
    role: '감염 뒤 역전사되는 유전정보를 담아요.',
    location: '성숙 capsid 내부',
    relationships: [
      'nucleocapsid 단백질과 결합하고 바이러스 효소들과 함께 capsid에 포장돼요.',
    ],
    modelRepresentation: '원뿔형 capsid 안의 두 개 코일로 표시해요.',
    simplification:
      'RNA 접힘, nucleocapsid 단백질과 효소는 별도 형상으로 그리지 않아요.',
    evidence: 'family-supported',
    sourceIds: ['ictv-retroviridae'],
  }),
  ...EXPANDED_FAMILY_STRUCTURE_EXPLANATIONS,
] as const;
