import { defineVirus, layer } from '../shared';

export const ANIMAL_CATALOG = [
  defineVirus({
    evidenceStatus: 'observed',
    id: 'aav2',
    name: '아데노연관바이러스 2형',
    shortName: 'AAV2',
    nameEn: 'Adeno-associated virus 2',
    particleState: '성숙 capsid 구조',
    category: '작은 parvovirus형 캡시드',
    genomeLabel: 'ssDNA',
    description: '작은 다면체 표면의 3회축 돌출부와 5회축 채널 위치를 강조해요.',
    feature: '3회축 돌출부와 5회축 채널',
    morphologyTags: ['animal', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'channel', 'genome'],
    layers: [layer('capsid', 'T=1 캡시드'), layer('genome', 'ssDNA')],
    sourceIds: ['pdb-1lp3'],
    modelBuilder: 'generic-icosahedral',
    geometryProfileId: 'ico-aav2-dimpled',
    simplifications: [
      '축별 표면 고저를 과장 없이 낮은 기하로 표현했어요.',
      '유전체 배치는 개념도예요.',
    ],
    displayLength: 3.8,
    sectionRadius: 1.85,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'canine-parvovirus',
    name: '개 파보바이러스',
    shortName: 'CPV',
    nameEn: 'Canine parvovirus',
    particleState: 'empty capsid 자료 중심',
    category: '작은 비외피 다면체 바이러스',
    genomeLabel: 'ssDNA 개념도',
    description: '빈 캡시드 구조에서 확인되는 5회축 원통과 표면 고리 영역을 보여줘요.',
    feature: '5회축 원통과 표면 고리',
    morphologyTags: ['animal', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'channel', 'genome'],
    layers: [layer('capsid', '빈 캡시드 참고'), layer('genome', 'ssDNA 개념도')],
    sourceIds: ['pdb-2cas'],
    modelBuilder: 'generic-icosahedral',
    geometryProfileId: 'ico-cpv-cylinders',
    simplifications: [
      '구조 출처는 empty capsid임을 명시해요.',
      '내부 유전체는 별도의 개념 표시예요.',
    ],
    displayLength: 3.9,
    sectionRadius: 1.9,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'pcv2',
    name: '돼지써코바이러스 2형',
    shortName: 'PCV2',
    nameEn: 'Porcine circovirus 2',
    particleState: 'VLP capsid 구조 참고',
    category: '매우 작은 원형 ssDNA 바이러스',
    genomeLabel: '원형 ssDNA 개념도',
    description:
      'VLP에서 확인된 작은 T=1 껍질과 안쪽 원형 DNA 공간을 서로 다른 근거 수준으로 구분해요.',
    feature: '작은 T=1 캡시드',
    morphologyTags: ['animal', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'genome'],
    layers: [layer('capsid', 'VLP T=1 캡시드'), layer('genome', '원형 ssDNA 개념도')],
    sourceIds: ['pdb-3jci'],
    modelBuilder: 'generic-icosahedral',
    geometryProfileId: 'ico-pcv2-small',
    simplifications: [
      '실제 상대 크기는 화면 확대 때문에 직접 비교할 수 없어요.',
      '원형 DNA는 닫힌 내부 선으로만 표시했어요.',
    ],
    displayLength: 3.4,
    sectionRadius: 1.65,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'hpv16',
    name: '인유두종바이러스 16형',
    shortName: 'HPV16',
    nameEn: 'Human papillomavirus 16',
    particleState: '성숙 VLP·capsid 구조 참고',
    category: '72 capsomer 다면체 바이러스',
    genomeLabel: '원형 dsDNA 개념도',
    description:
      '오각형 L1 capsomer가 만드는 T=7d 배열과 소량의 L2 위치를 구조적으로 살펴봐요.',
    feature: '오각 capsomer 반복 배열',
    morphologyTags: ['animal', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'genome'],
    layers: [
      layer('capsid', 'L1 capsomer 캡시드'),
      layer('genome', '원형 dsDNA 개념도'),
    ],
    sourceIds: ['pdb-7kzf'],
    modelBuilder: 'generic-icosahedral',
    geometryProfileId: 'ico-papilloma-pentamers',
    simplifications: [
      'VLP 구조 참고 범위를 명시하고 실제 유전체 패킹으로 해석하지 않아요.',
      '72개 전체를 화면용 저밀도 배열로 줄였어요.',
    ],
    displayLength: 4.5,
    sectionRadius: 2.2,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'sv40',
    name: '시미안바이러스 40',
    shortName: 'SV40',
    nameEn: 'Simian virus 40',
    particleState: '성숙 capsid',
    category: 'polyomavirus 오각 capsomer 입자',
    genomeLabel: '원형 dsDNA',
    description:
      '오각형 VP1 capsomer가 서로 다른 주변 환경에 놓이는 구형 다면체 표면을 보여줘요.',
    feature: 'VP1 오각 capsomer 배열',
    morphologyTags: ['animal', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'genome'],
    layers: [layer('capsid', 'VP1 캡시드'), layer('genome', '원형 dsDNA')],
    sourceIds: ['pdb-1sva'],
    modelBuilder: 'generic-icosahedral',
    geometryProfileId: 'ico-polyoma-sv40',
    simplifications: [
      'capsomer 간 연결을 원자 수준으로 재현하지 않았어요.',
      '히스톤 결합 DNA는 단순 닫힌 곡선이에요.',
    ],
    displayLength: 4.4,
    sectionRadius: 2.15,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'murine-polyomavirus',
    name: '쥐 폴리오마바이러스',
    shortName: 'MPyV',
    nameEn: 'Murine polyomavirus',
    particleState: '성숙 capsid',
    category: 'polyomavirus 오각 capsomer 입자',
    genomeLabel: '원형 dsDNA',
    description:
      'SV40과 닮은 오각 capsomer 원리를 유지하며 더 낮은 표면 융기를 보여줘요.',
    feature: '낮은 VP1 오각 capsomer',
    morphologyTags: ['animal', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'genome'],
    layers: [layer('capsid', 'VP1 캡시드'), layer('genome', '원형 dsDNA')],
    sourceIds: ['pdb-1sie'],
    modelBuilder: 'generic-icosahedral',
    geometryProfileId: 'ico-polyoma-murine',
    simplifications: [
      'SV40과의 실제 구조 유사성을 유지했어요.',
      '종 차이는 확인 가능한 표면 높이 수준에서만 표현했어요.',
    ],
    displayLength: 4.4,
    sectionRadius: 2.15,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'norwalk',
    name: '노워크바이러스',
    shortName: 'Norwalk',
    nameEn: 'Norwalk virus',
    particleState: 'VLP capsid 구조 참고',
    category: '돌출 P-domain 캘리시바이러스',
    genomeLabel: 'ssRNA(+) 개념도',
    description: '낮은 shell 층 위로 짝을 이룬 P-domain이 솟는 표면을 강조해요.',
    feature: 'shell 위의 돌출 P-domain',
    morphologyTags: ['animal', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'genome'],
    layers: [
      layer('capsid', 'S-domain shell'),
      layer('surface-protein', 'P-domain'),
      layer('genome', 'ssRNA(+) 개념도'),
    ],
    sourceIds: ['pdb-1ihm'],
    modelBuilder: 'generic-icosahedral',
    geometryProfileId: 'ico-calici-protruding',
    simplifications: [
      'VLP 캡시드 자료이며 유전체 위치는 실측 재현이 아니에요.',
      'P-domain dimer를 짧은 이중 돌기로 줄였어요.',
    ],
    displayLength: 4.4,
    sectionRadius: 2.05,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'rhdv',
    name: '토끼출혈병바이러스',
    shortName: 'RHDV',
    nameEn: 'Rabbit hemorrhagic disease virus',
    particleState: '성숙 capsid 구조',
    category: '돌출 P-domain 캘리시바이러스',
    genomeLabel: 'ssRNA(+)',
    description:
      '캘리시바이러스 공통 shell 위에 더 넓게 벌어진 돌출 도메인을 보여줘요.',
    feature: '넓게 벌어진 P-domain',
    morphologyTags: ['animal', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'genome'],
    layers: [
      layer('capsid', 'S-domain shell'),
      layer('surface-protein', 'P-domain'),
      layer('genome', 'ssRNA(+)'),
    ],
    sourceIds: ['pdb-3j1p'],
    modelBuilder: 'generic-icosahedral',
    geometryProfileId: 'ico-rhdv-protruding',
    simplifications: [
      'Norwalk와의 계열 유사성을 유지했어요.',
      '돌출 도메인 사이 홈을 저밀도 배열로 표현했어요.',
    ],
    displayLength: 4.5,
    sectionRadius: 2.08,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'astrovirus-1',
    name: '사람 아스트로바이러스 1형',
    shortName: 'HAstV-1',
    nameEn: 'Human astrovirus 1',
    particleState: '성숙 capsid 구성 참고',
    category: '성숙 spike 보유 아스트로바이러스',
    genomeLabel: 'ssRNA(+) 개념도',
    description:
      'HAstV-1 성숙 capsid 단백질 구조를 근거로 둥근 shell과 제한된 수의 표면 spike를 구분해요.',
    feature: '성숙 입자의 표면 spike',
    morphologyTags: ['animal', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'spike', 'genome'],
    layers: [
      layer('capsid', '성숙 shell'),
      layer('surface-protein', '표면 spike'),
      layer('genome', 'ssRNA(+) 개념도'),
    ],
    sourceIds: ['pdb-5ewn'],
    modelBuilder: 'generic-icosahedral',
    geometryProfileId: 'ico-astro-spiked',
    simplifications: [
      'HAstV-1 capsid 단백질 구조를 입자 전체의 저밀도 형태로 확장했어요.',
      'capsid 단백질 절단 상태는 색으로 구분하지 않았어요.',
    ],
    displayLength: 4.2,
    sectionRadius: 2,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'hbv',
    name: 'B형간염바이러스',
    shortName: 'HBV',
    nameEn: 'Hepatitis B virus',
    particleState: '완전한 Dane particle',
    category: '외피·코어 보유 간염바이러스',
    genomeLabel: '부분 이중가닥 원형 DNA',
    description:
      '표면항원만의 빈 입자가 아니라 외피 안에 정이십면체 코어가 있는 Dane particle을 보여줘요.',
    feature: '외피 안의 정이십면체 코어',
    morphologyTags: ['animal', 'enveloped', 'icosahedral'],
    silhouette: 'envelope',
    parts: ['envelope', 'spike', 'core-capsid', 'capsomer', 'genome'],
    layers: [
      layer('envelope', 'HBsAg 외피'),
      layer('surface-protein', '표면항원'),
      layer('core-capsid', 'HBc 코어'),
      layer('genome', '부분 dsDNA'),
    ],
    sourceIds: ['pdb-6htx', 'ictv-hepadnaviridae'],
    modelBuilder: 'hbv',
    geometryProfileId: 'enveloped-hbv-dane',
    simplifications: [
      'Dane particle 상태로 한정했어요.',
      '역전사효소와 DNA/RNA 중간체는 표시하지 않았어요.',
    ],
    displayLength: 4.5,
    sectionRadius: 2.15,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'sindbis',
    name: '신드비스바이러스',
    shortName: 'Sindbis',
    nameEn: 'Sindbis virus',
    particleState: '성숙 enveloped virion',
    category: '정렬된 glycoprotein 외피 alphavirus',
    genomeLabel: 'ssRNA(+)',
    description:
      '정이십면체 질서로 배열된 외피 glycoprotein과 내부 nucleocapsid를 대응시켜 보여줘요.',
    feature: '외피 spike와 코어의 대칭 대응',
    morphologyTags: ['animal', 'enveloped', 'icosahedral'],
    silhouette: 'envelope',
    parts: ['envelope', 'spike', 'nucleocapsid', 'capsomer', 'genome'],
    layers: [
      layer('envelope', '지질 외피'),
      layer('surface-protein', 'glycoprotein spike'),
      layer('nucleocapsid', '내부 코어'),
      layer('genome', 'ssRNA(+)'),
    ],
    sourceIds: ['pdb-6imm'],
    modelBuilder: 'alphavirus',
    geometryProfileId: 'enveloped-alphavirus-sindbis',
    simplifications: [
      'glycoprotein trimer를 원뿔형 반복 단위로 줄였어요.',
      '막 지질과 RNA 패킹은 개념화했어요.',
    ],
    displayLength: 4.8,
    sectionRadius: 2.3,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'semliki-forest',
    name: '셈리키숲바이러스',
    shortName: 'SFV',
    nameEn: 'Semliki Forest virus',
    particleState: '성숙 enveloped virion',
    category: '정렬된 glycoprotein 외피 alphavirus',
    genomeLabel: 'ssRNA(+)',
    description:
      'Sindbis와 닮은 외피-코어 대응을 유지하면서 더 조밀한 spike 표면을 보여줘요.',
    feature: '조밀한 alphavirus spike lattice',
    morphologyTags: ['animal', 'enveloped', 'icosahedral'],
    silhouette: 'envelope',
    parts: ['envelope', 'spike', 'nucleocapsid', 'capsomer', 'genome'],
    layers: [
      layer('envelope', '지질 외피'),
      layer('surface-protein', 'glycoprotein spike'),
      layer('nucleocapsid', '내부 코어'),
      layer('genome', 'ssRNA(+)'),
    ],
    sourceIds: ['emd-sfv', 'ictv-togaviridae'],
    modelBuilder: 'alphavirus',
    geometryProfileId: 'enveloped-alphavirus-sfv',
    simplifications: [
      'Sindbis와의 계열 유사성을 의도적으로 유지했어요.',
      'spike 밀도와 코어 비율만 구조 근거 범위에서 구분했어요.',
    ],
    displayLength: 4.8,
    sectionRadius: 2.3,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'flock-house',
    name: '플록하우스바이러스',
    shortName: 'FHV',
    nameEn: 'Flock House virus',
    particleState: 'RNA 보유 실제 입자',
    category: 'T=3 곤충 nodavirus',
    genomeLabel: '2분절 ssRNA(+)',
    description: '조밀한 T=3 캡시드와 안쪽 RNA 밀도 관계를 살펴봐요.',
    feature: '곤충 nodavirus T=3 표면',
    morphologyTags: ['animal', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'genome'],
    layers: [layer('capsid', 'T=3 캡시드'), layer('genome', '2분절 ssRNA(+)')],
    sourceIds: ['pdb-4ftb'],
    modelBuilder: 'generic-icosahedral',
    geometryProfileId: 'ico-fhv-t3',
    simplifications: [
      'RNA 밀도를 개별 뉴클레오타이드로 그리지 않았어요.',
      '캡시드 내부 절단 펩타이드는 생략했어요.',
    ],
    displayLength: 4,
    sectionRadius: 1.98,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'ibdv',
    name: '감염성F낭병바이러스',
    shortName: 'IBDV',
    nameEn: 'Infectious bursal disease virus',
    particleState: '성숙 이중층 입자',
    category: '비외피 이중층 birnavirus',
    genomeLabel: '2분절 dsRNA',
    description: '바깥 VP2 층과 안쪽 단백질층, 두 RNA 분절을 차례로 분리해요.',
    feature: '두 단백질층과 dsRNA',
    morphologyTags: ['animal', 'icosahedral', 'complex'],
    silhouette: 'polyhedron',
    parts: ['outer-capsid', 'core-capsid', 'capsomer', 'genome'],
    layers: [
      layer('outer-capsid', '외부 VP2 층'),
      layer('core-capsid', '내부 단백질층'),
      layer('genome', '2분절 dsRNA'),
    ],
    sourceIds: ['pdb-2df7'],
    modelBuilder: 'generic-layered',
    geometryProfileId: 'layered-ibdv-double',
    simplifications: [
      '두 층의 단백질 종류를 연속 shell로 줄였어요.',
      '두 dsRNA 분절은 이중 선으로 표시했어요.',
    ],
    displayLength: 4.6,
    sectionRadius: 2.18,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'bluetongue',
    name: '블루텅바이러스',
    shortName: 'BTV',
    nameEn: 'Bluetongue virus',
    particleState: '성숙 다층 입자',
    category: '다층 orbivirus',
    genomeLabel: '10분절 dsRNA',
    description: '바깥 캡시드, 중간 shell, transcription core를 세 겹으로 분리해요.',
    feature: '세 겹의 단백질 껍질',
    morphologyTags: ['animal', 'icosahedral', 'complex'],
    silhouette: 'polyhedron',
    parts: ['outer-capsid', 'middle-capsid', 'core-capsid', 'spike', 'genome'],
    layers: [
      layer('outer-capsid', '바깥 캡시드'),
      layer('middle-capsid', '중간 shell'),
      layer('core-capsid', '전사 코어'),
      layer('genome', '10분절 dsRNA'),
    ],
    sourceIds: ['pdb-2btv'],
    modelBuilder: 'generic-layered',
    geometryProfileId: 'layered-bluetongue-triple',
    simplifications: [
      '각 층의 실제 화학량론은 렌더 반복 수와 다릅니다.',
      '열 분절은 짧은 내부 선 묶음으로 표시했어요.',
    ],
    displayLength: 5,
    sectionRadius: 2.4,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'reovirus-t3d',
    name: '포유류 오르토레오바이러스 T3D',
    shortName: 'Reovirus T3D',
    nameEn: 'Mammalian orthoreovirus type 3 Dearing',
    particleState: '성숙 virion',
    category: '다층 reovirus',
    genomeLabel: '10분절 dsRNA',
    description: '바깥 돌기, 중간 캡시드와 코어가 겹친 큰 비외피 입자를 보여줘요.',
    feature: '꼭짓점 turret와 다층 코어',
    morphologyTags: ['animal', 'icosahedral', 'complex'],
    silhouette: 'polyhedron',
    parts: ['outer-capsid', 'middle-capsid', 'core-capsid', 'turret', 'genome'],
    layers: [
      layer('outer-capsid', '외부 캡시드'),
      layer('middle-capsid', '중간 캡시드'),
      layer('core-capsid', '코어'),
      layer('surface-protein', '꼭짓점 turret'),
      layer('genome', '10분절 dsRNA'),
    ],
    sourceIds: ['pdb-1ej6'],
    modelBuilder: 'generic-layered',
    geometryProfileId: 'layered-reovirus-turret',
    simplifications: [
      '꼭짓점 복합체를 짧은 turret 기하로 줄였어요.',
      '분절 RNA와 전사효소 배치는 개념도예요.',
    ],
    displayLength: 5.2,
    sectionRadius: 2.48,
  }),
] as const;
