import { defineVirus, layer } from '../shared';

export const ARCHAEA_CATALOG = [
  defineVirus({
    evidenceStatus: 'observed',
    id: 'ssv1',
    name: 'Sulfolobus 방추형 바이러스 1',
    shortName: 'SSV1',
    nameEn: 'Sulfolobus spindle-shaped virus 1',
    particleState: '성숙 spindle-shaped virion',
    category: '고세균 방추형 바이러스',
    genomeLabel: '원형 dsDNA',
    description:
      '가운데가 부풀고 양끝이 좁아지는 방추형 몸체와 한쪽 말단 섬유를 보여줘요.',
    feature: '방추형 몸체와 극성 말단',
    morphologyTags: ['archaea', 'complex'],
    silhouette: 'spindle',
    parts: ['envelope', 'capsid', 'terminal-tail', 'genome'],
    layers: [
      layer('envelope', '단백질·지질성 외곽'),
      layer('capsid', '방추형 몸체'),
      layer('tail', '말단 섬유'),
      layer('genome', '원형 dsDNA'),
    ],
    sourceIds: ['ictv-fuselloviridae'],
    modelBuilder: 'generic-spindle',
    geometryProfileId: 'spindle-ssv1-one-tail',
    simplifications: [
      '한쪽 말단의 가는 부속 구조만 강조했어요.',
      '외곽 단백질 배열과 지질 조성은 연속 표면으로 줄였어요.',
    ],
    displayLength: 6.2,
    sectionRadius: 1.65,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'sirv2',
    name: 'Sulfolobus islandicus 막대형 바이러스 2',
    shortName: 'SIRV2',
    nameEn: 'Sulfolobus islandicus rod-shaped virus 2',
    particleState: '성숙 rod-shaped virion',
    category: '고세균 막대형 바이러스',
    genomeLabel: '선형 dsDNA',
    description: '길고 단단한 막대형 피복과 양끝의 세 갈래 섬유 구조를 구분해요.',
    feature: '막대 양끝의 세 갈래 섬유',
    morphologyTags: ['archaea', 'helical', 'complex'],
    silhouette: 'rod',
    parts: ['capsid', 'coat-protein', 'terminal-tail', 'genome'],
    layers: [
      layer('capsid', '막대형 피복'),
      layer('tail', '양끝 섬유'),
      layer('genome', '선형 dsDNA'),
    ],
    sourceIds: ['ictv-rudiviridae'],
    modelBuilder: 'generic-rod',
    geometryProfileId: 'rod-sirv2-fibers',
    simplifications: [
      '강체 막대로 유지하며 필라멘트 굽힘을 적용하지 않아요.',
      '말단 섬유의 단백질 세부는 분절 선으로 줄였어요.',
    ],
    displayLength: 8,
    sectionRadius: 0.72,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'stiv',
    name: 'Sulfolobus turreted icosahedral virus',
    shortName: 'STIV',
    nameEn: 'Sulfolobus turreted icosahedral virus',
    particleState: '성숙 turreted virion',
    category: '고세균 turret형 다면체 바이러스',
    genomeLabel: '원형 dsDNA',
    description: '다면체 각 꼭짓점의 굵은 turret와 캡시드 안쪽 막을 함께 보여줘요.',
    feature: '꼭짓점 turret와 내부 막',
    morphologyTags: ['archaea', 'icosahedral', 'complex'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'turret', 'inner-membrane', 'genome'],
    layers: [
      layer('capsid', '다면체 캡시드'),
      layer('surface-protein', '꼭짓점 turret'),
      layer('inner-membrane', '내부 막'),
      layer('genome', '원형 dsDNA'),
    ],
    sourceIds: ['pdb-3j31'],
    modelBuilder: 'layered-capsid',
    geometryProfileId: 'layered-stiv-turret',
    simplifications: [
      'turret의 내부 채널은 속이 빈 굵은 돌기로 표시했어요.',
      '막과 DNA의 분자 배열은 개념화했어요.',
    ],
    displayLength: 5.2,
    sectionRadius: 2.35,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'atv',
    name: 'Acidianus 양꼬리바이러스',
    shortName: 'ATV',
    nameEn: 'Acidianus two-tailed virus',
    particleState: '세포 밖 양꼬리 성숙 상태',
    category: '고세균 양꼬리 방추형 바이러스',
    genomeLabel: '선형 dsDNA',
    description:
      '방추형 몸체 양끝에서 길게 자란 꼬리를 가진 세포 밖 성숙 상태를 보여줘요.',
    feature: '방추형 몸체의 양쪽 꼬리',
    morphologyTags: ['archaea', 'complex'],
    silhouette: 'spindle',
    parts: ['envelope', 'capsid', 'terminal-tail', 'genome'],
    layers: [
      layer('envelope', '방추형 외곽'),
      layer('capsid', '중앙 몸체'),
      layer('tail', '양쪽 꼬리'),
      layer('genome', '선형 dsDNA'),
    ],
    sourceIds: ['ictv-bicaudaviridae'],
    modelBuilder: 'generic-spindle',
    geometryProfileId: 'spindle-atv-two-tail',
    simplifications: [
      '세포 밖에서 꼬리가 발달한 상태로 고정했어요.',
      '꼬리 길이와 표면 미세섬유는 화면용으로 줄였어요.',
    ],
    displayLength: 8.4,
    sectionRadius: 1.75,
  }),
] as const;
