import type { CatalogEntryInput } from '../shared';
import { defineVirus, layer } from '../shared';

type EmergingInput = Omit<
  CatalogEntryInput,
  | 'parts'
  | 'layers'
  | 'sourceIds'
  | 'silhouette'
  | 'modelBuilder'
  | 'geometryProfileId'
  | 'displayLength'
  | 'sectionRadius'
  | 'simplifications'
>;

const FILOVIRUS_SOURCE_IDS = ['ictv-orthoebolavirus'] as const;
const CORONAVIRUS_SOURCE_IDS = ['cdc-human-coronavirus', 'ictv-coronaviridae'] as const;

function filovirus(input: EmergingInput) {
  return defineVirus({
    ...input,
    taxonomyName: input.taxonomyName,
    silhouette: 'filament',
    parts: ['envelope', 'spike', 'matrix', 'nucleocapsid', 'genome'],
    layers: [
      layer('envelope', '지질 외피'),
      layer('surface-protein', '표면 당단백질'),
      layer('matrix', 'Matrix'),
      layer('nucleocapsid', '나선형 RNP'),
      layer('genome', 'ssRNA(-)'),
    ],
    sourceIds: FILOVIRUS_SOURCE_IDS,
    modelBuilder: 'filovirus',
    geometryProfileId: 'filovirus-v3.5',
    representation: 'family-concept-procedural',
    simplifications: [
      '길이와 굽힘은 관찰된 입자 형태 가운데 하나를 고정한 대표 표본이에요.',
      '종별 직접 입체 자료가 부족한 세부는 계열 공통 개념 표현으로 구분해요.',
    ],
    displayLength: 8.2,
    sectionRadius: 0.72,
  });
}

function coronavirus(input: EmergingInput) {
  return defineVirus({
    ...input,
    silhouette: 'envelope',
    parts: ['envelope', 'spike', 'matrix', 'nucleocapsid', 'genome'],
    layers: [
      layer('envelope', '지질 외피'),
      layer('surface-protein', '표면 단백질'),
      layer('matrix', '막 안쪽 단백질층'),
      layer('nucleocapsid', 'RNA-단백질 복합체'),
      layer('genome', 'ssRNA(+)'),
    ],
    sourceIds: CORONAVIRUS_SOURCE_IDS,
    modelBuilder: 'coronavirus',
    geometryProfileId: 'coronavirus-v3.5',
    representation: 'family-concept-procedural',
    simplifications: [
      '표면 돌기 수와 RNA 접힘은 관찰용으로 줄였어요.',
      '종·계통별 차이가 확인되지 않은 입자 외형은 같은 계열 모델을 사용해요.',
    ],
    displayLength: 5.2,
    sectionRadius: 2.35,
  });
}

export const EMERGING_CATALOG = [
  filovirus({
    id: 'ebola-virus',
    name: '에볼라 바이러스',
    shortName: 'EBOV',
    nameEn: 'Ebola virus',
    taxonomyName: 'Orthoebolavirus zairense',
    aliases: ['자이르 에볼라바이러스', 'Zaire ebolavirus'],
    particleState: '약 805 nm 대표 감염성 필라멘트',
    category: '필로바이러스 · 에볼라 계열',
    genomeLabel: '비분절 ssRNA(-)',
    description: '외피와 matrix 안쪽의 나선형 RNP를 굽은 필라멘트 표본으로 관찰해요.',
    feature: '96–98 nm 폭의 굽은 필라멘트와 나선 RNP',
    morphologyTags: ['animal', 'enveloped', 'helical'],
    evidenceStatus: 'observed',
  }),
  filovirus({
    id: 'sudan-virus',
    name: '수단 바이러스',
    shortName: 'SUDV',
    nameEn: 'Sudan virus',
    taxonomyName: 'Orthoebolavirus sudanense',
    particleState: '성숙 필라멘트 개념 표본',
    category: '필로바이러스 · 에볼라 계열',
    genomeLabel: '비분절 ssRNA(-)',
    description:
      '에볼라 계열 공통 층 구성을 사용하며 종별 미확인 세부는 구분해 표시해요.',
    feature: '외피·matrix·나선 RNP',
    morphologyTags: ['animal', 'enveloped', 'helical'],
    evidenceStatus: 'conceptual',
  }),
  filovirus({
    id: 'bundibugyo-virus',
    name: '분디부교 바이러스',
    shortName: 'BDBV',
    nameEn: 'Bundibugyo virus',
    taxonomyName: 'Orthoebolavirus bundibugyoense',
    particleState: '성숙 필라멘트 개념 표본',
    category: '필로바이러스 · 에볼라 계열',
    genomeLabel: '비분절 ssRNA(-)',
    description: '계열 공통 필라멘트 외형과 내부 RNP의 층 관계를 관찰해요.',
    feature: '굽은 외피와 나선 RNP',
    morphologyTags: ['animal', 'enveloped', 'helical'],
    evidenceStatus: 'conceptual',
  }),
  filovirus({
    id: 'tai-forest-virus',
    name: '타이포레스트 바이러스',
    shortName: 'TAFV',
    nameEn: 'Taï Forest virus',
    taxonomyName: 'Orthoebolavirus taiense',
    particleState: '성숙 필라멘트 개념 표본',
    category: '필로바이러스 · 에볼라 계열',
    genomeLabel: '비분절 ssRNA(-)',
    description: '계열 공통 구조와 종별 자료 한계를 함께 표시해요.',
    feature: '외피·matrix·나선 RNP',
    morphologyTags: ['animal', 'enveloped', 'helical'],
    evidenceStatus: 'conceptual',
  }),
  filovirus({
    id: 'reston-virus',
    name: '레스턴 바이러스',
    shortName: 'RESTV',
    nameEn: 'Reston virus',
    taxonomyName: 'Orthoebolavirus restonense',
    particleState: '성숙 필라멘트 개념 표본',
    category: '필로바이러스 · 에볼라 계열',
    genomeLabel: '비분절 ssRNA(-)',
    description: '계열 공통 필라멘트 구조를 사용하고 종별 세부 근거 범위를 밝혀요.',
    feature: '외피·matrix·나선 RNP',
    morphologyTags: ['animal', 'enveloped', 'helical'],
    evidenceStatus: 'conceptual',
  }),
  filovirus({
    id: 'bombali-virus',
    name: '봄발리 바이러스',
    shortName: 'BOMV',
    nameEn: 'Bombali virus',
    taxonomyName: 'Orthoebolavirus bombaliense',
    particleState: '계열 공통 개념 표본',
    category: '필로바이러스 · 에볼라 계열',
    genomeLabel: '비분절 ssRNA(-)',
    description: '종별 직접 입체 근거가 부족해 확인된 계열 공통 층만 표현해요.',
    feature: '자료 범위를 밝힌 필로바이러스 공통 구조',
    morphologyTags: ['animal', 'enveloped', 'helical'],
    evidenceStatus: 'conceptual',
  }),
  defineVirus({
    id: 'hiv-1',
    name: '사람면역결핍바이러스 1형',
    shortName: 'HIV-1',
    nameEn: 'Human immunodeficiency virus 1',
    particleState: '성숙 입자',
    category: 'Lentivirus · 성숙 원뿔형 코어',
    genomeLabel: '2분자 ssRNA(+)',
    description: '지질 외피·matrix와 분리된 성숙 원뿔형 capsid 내부의 RNA를 관찰해요.',
    feature: '외피 안쪽의 비대칭 원뿔형 capsid',
    morphologyTags: ['animal', 'enveloped'],
    silhouette: 'envelope',
    parts: ['envelope', 'spike', 'matrix', 'capsid', 'genome'],
    layers: [
      layer('envelope', '지질 외피'),
      layer('surface-protein', 'Env'),
      layer('matrix', 'Matrix'),
      layer('capsid', '성숙 원뿔형 capsid'),
      layer('genome', '2분자 ssRNA'),
    ],
    sourceIds: ['ictv-retroviridae', 'pdb-3j3q'],
    modelBuilder: 'lentivirus',
    geometryProfileId: 'lentivirus-v3.5',
    evidenceStatus: 'observed',
    simplifications: [
      'PDB 3J3Q의 capsid 개념을 전체 입자의 원자 좌표로 취급하지 않아요.',
      'Env 수와 RNA 포장은 화면용 개념 표현이에요.',
    ],
    displayLength: 4.8,
    sectionRadius: 2.25,
  }),
  defineVirus({
    id: 'hiv-2',
    name: '사람면역결핍바이러스 2형',
    shortName: 'HIV-2',
    nameEn: 'Human immunodeficiency virus 2',
    particleState: '성숙 입자 계열 개념 표본',
    category: 'Lentivirus · 계열 공통 구조',
    genomeLabel: '2분자 ssRNA(+)',
    description: 'HIV-2 정체성과 렌티바이러스 공통 층을 구분해 표시해요.',
    feature: '외피·matrix·capsid의 계열 공통 배치',
    morphologyTags: ['animal', 'enveloped'],
    silhouette: 'envelope',
    parts: ['envelope', 'spike', 'matrix', 'capsid', 'genome'],
    layers: [
      layer('envelope', '지질 외피'),
      layer('surface-protein', 'Env'),
      layer('matrix', 'Matrix'),
      layer('capsid', '성숙 capsid 개념'),
      layer('genome', '2분자 ssRNA'),
    ],
    sourceIds: ['ictv-retroviridae', 'nih-hiv2'],
    modelBuilder: 'lentivirus',
    geometryProfileId: 'lentivirus-v3.5',
    evidenceStatus: 'conceptual',
    representation: 'family-concept-procedural',
    simplifications: [
      'HIV-1 자료로 HIV-2의 종별 세부가 모두 확인됐다고 해석하지 않아요.',
      'Env 수와 RNA 포장은 화면용 개념 표현이에요.',
    ],
    displayLength: 4.8,
    sectionRadius: 2.25,
  }),
  coronavirus({
    id: 'hcov-229e',
    name: '사람 코로나바이러스 229E',
    shortName: 'HCoV-229E',
    nameEn: 'Human coronavirus 229E',
    particleState: '성숙 입자 계열 개념 표본',
    category: 'Alphacoronavirus · 사람 코로나바이러스',
    genomeLabel: 'ssRNA(+)',
    description: '사람 알파코로나바이러스의 외피·표면 단백질·RNP 층을 관찰해요.',
    feature: '외피와 왕관 모양 표면 돌기',
    morphologyTags: ['animal', 'enveloped'],
    evidenceStatus: 'conceptual',
  }),
  coronavirus({
    id: 'hcov-nl63',
    name: '사람 코로나바이러스 NL63',
    shortName: 'HCoV-NL63',
    nameEn: 'Human coronavirus NL63',
    particleState: '성숙 입자 계열 개념 표본',
    category: 'Alphacoronavirus · 사람 코로나바이러스',
    genomeLabel: 'ssRNA(+)',
    description: 'NL63의 정체성과 계열 공통 입자 구조를 구분해 표시해요.',
    feature: '외피와 왕관 모양 표면 돌기',
    morphologyTags: ['animal', 'enveloped'],
    evidenceStatus: 'conceptual',
  }),
  coronavirus({
    id: 'hcov-oc43',
    name: '사람 코로나바이러스 OC43',
    shortName: 'HCoV-OC43',
    nameEn: 'Human coronavirus OC43',
    particleState: '성숙 입자 계열 개념 표본',
    category: 'Betacoronavirus · 사람 코로나바이러스',
    genomeLabel: 'ssRNA(+)',
    description: 'OC43의 정체성과 계열 공통 외피·RNP 구조를 함께 확인해요.',
    feature: '외피와 RNA-단백질 복합체',
    morphologyTags: ['animal', 'enveloped'],
    evidenceStatus: 'conceptual',
  }),
  coronavirus({
    id: 'hcov-hku1',
    name: '사람 코로나바이러스 HKU1',
    shortName: 'HCoV-HKU1',
    nameEn: 'Human coronavirus HKU1',
    particleState: '성숙 입자 계열 개념 표본',
    category: 'Betacoronavirus · 사람 코로나바이러스',
    genomeLabel: 'ssRNA(+)',
    description: 'HKU1의 정체성과 계열 공통 입자 구조를 구분해 표시해요.',
    feature: '외피와 RNA-단백질 복합체',
    morphologyTags: ['animal', 'enveloped'],
    evidenceStatus: 'conceptual',
  }),
  coronavirus({
    id: 'sars-cov',
    name: 'SARS 코로나바이러스',
    shortName: 'SARS-CoV',
    nameEn: 'SARS coronavirus',
    particleState: '성숙 입자 개념 표본',
    category: 'Betacoronavirus · 사람 코로나바이러스',
    genomeLabel: 'ssRNA(+)',
    description:
      'SARS-CoV의 외피와 표면 단백질, 내부 RNP를 계열 근거 범위 안에서 표현해요.',
    feature: '외피·표면 돌기·RNP',
    morphologyTags: ['animal', 'enveloped'],
    evidenceStatus: 'conceptual',
  }),
  coronavirus({
    id: 'mers-cov',
    name: 'MERS 코로나바이러스',
    shortName: 'MERS-CoV',
    nameEn: 'MERS coronavirus',
    particleState: '성숙 입자 개념 표본',
    category: 'Betacoronavirus · 사람 코로나바이러스',
    genomeLabel: 'ssRNA(+)',
    description: 'MERS-CoV의 정체성과 계열 공통 입자 구조를 함께 표시해요.',
    feature: '외피·표면 돌기·RNP',
    morphologyTags: ['animal', 'enveloped'],
    evidenceStatus: 'conceptual',
  }),
  coronavirus({
    id: 'sars-cov-2',
    name: 'SARS-CoV-2',
    shortName: 'SARS-CoV-2',
    nameEn: 'Severe acute respiratory syndrome coronavirus 2',
    particleState: '성숙 입자 개념 표본',
    category: 'Betacoronavirus · 사람 코로나바이러스',
    genomeLabel: 'ssRNA(+)',
    description:
      '외피·표면 단백질과 내부 RNA-단백질 복합체를 구분하고 변이 표본을 별도로 비교해요.',
    feature: '표면 spike와 내부 RNP',
    morphologyTags: ['animal', 'enveloped'],
    evidenceStatus: 'observed',
  }),
] as const;
