import type { CatalogEntryInput } from '../shared';
import { defineVirus, layer } from '../shared';

type BaseInput = Omit<
  CatalogEntryInput,
  | 'parts'
  | 'layers'
  | 'sourceIds'
  | 'silhouette'
  | 'modelBuilder'
  | 'geometryProfileId'
  | 'displayLength'
  | 'sectionRadius'
  | 'simplifications'
  | 'representation'
>;

function humanRnp(
  input: BaseInput,
  profileId: string,
  sourceIds: readonly string[],
  matrix = true,
) {
  return defineVirus({
    ...input,
    silhouette: 'envelope',
    parts: matrix
      ? ['envelope', 'spike', 'matrix', 'nucleocapsid', 'genome']
      : ['envelope', 'spike', 'nucleocapsid', 'genome'],
    layers: [
      layer('envelope', '지질 외피'),
      layer('surface-protein', '표면 당단백질'),
      ...(matrix ? [layer('matrix', 'Matrix 단백질층')] : []),
      layer('nucleocapsid', 'RNA-단백질 복합체'),
      layer('genome', input.genomeLabel),
    ],
    sourceIds,
    modelBuilder: 'human-rnp',
    geometryProfileId: profileId,
    representation:
      input.evidenceStatus === 'observed'
        ? 'source-informed-procedural'
        : 'family-concept-procedural',
    simplifications: [
      '계열 구조를 절차 기하로 단순화하며 원자 배열과 실제 조성비는 재현하지 않아요.',
      '종별 구조 차이가 확인되지 않은 부분은 같은 profile을 공유해요.',
      '화면의 표면 단백질 반복 수는 실제 화학량론을 뜻하지 않아요.',
    ],
    displayLength: 4.9,
    sectionRadius: 2.35,
  });
}

function reused(
  input: BaseInput & {
    readonly builder: CatalogEntryInput['modelBuilder'];
    readonly profileId: string;
    readonly sourceIds: readonly string[];
    readonly silhouette: CatalogEntryInput['silhouette'];
    readonly parts: CatalogEntryInput['parts'];
    readonly layers: CatalogEntryInput['layers'];
    readonly displayLength: number;
    readonly sectionRadius: number;
  },
) {
  const {
    builder,
    profileId,
    sourceIds,
    silhouette,
    parts,
    layers,
    displayLength,
    sectionRadius,
    ...base
  } = input;
  return defineVirus({
    ...base,
    silhouette,
    parts,
    layers,
    sourceIds,
    modelBuilder: builder,
    geometryProfileId: profileId,
    representation: 'family-concept-procedural',
    simplifications: [
      '같은 계열의 검증된 renderer를 공유하며 근거 없는 종별 장식은 추가하지 않아요.',
      '표면 단백질 수와 내부 핵산 배치는 관찰용으로 줄였어요.',
    ],
    displayLength,
    sectionRadius,
  });
}

const envelopeLayers = [
  layer('envelope', '지질 외피'),
  layer('surface-protein', '표면 당단백질'),
  layer('matrix', 'Matrix'),
  layer('nucleocapsid', '나선형 RNP'),
  layer('genome', 'RNA genome'),
] as const;

const herpesParts = [
  'envelope',
  'spike',
  'tegument',
  'capsid',
  'capsomer',
  'genome',
] as const;
const herpesLayers = [
  layer('envelope', '지질 외피'),
  layer('surface-protein', '외피 당단백질'),
  layer('tegument', 'Tegument'),
  layer('capsid', '정이십면체 capsid'),
  layer('genome', 'dsDNA'),
] as const;

const poxParts = ['envelope', 'core-wall', 'lateral-body', 'genome'] as const;
const poxLayers = [
  layer('membrane', '성숙 입자 막'),
  layer('core-wall', 'Core wall'),
  layer('lateral-body', 'Lateral body'),
  layer('genome', 'dsDNA'),
] as const;

const influenzaParts = ['envelope', 'spike', 'matrix', 'rnp', 'genome'] as const;
const influenzaLayers = [
  layer('envelope', '지질 외피'),
  layer('surface-protein', 'HA·NA·M2'),
  layer('matrix', 'M1 matrix'),
  layer('nucleocapsid', '8개 vRNP'),
] as const;

const alphaParts = ['envelope', 'spike', 'nucleocapsid', 'capsomer', 'genome'] as const;
const alphaLayers = [
  layer('envelope', '지질 외피'),
  layer('surface-protein', 'E1/E2 spike'),
  layer('nucleocapsid', '정이십면체 nucleocapsid'),
  layer('genome', 'ssRNA(+)'),
] as const;

export const HUMAN_EXPANSION_IDS = [
  'marburg-virus',
  'rabies-virus',
  'dengue-virus',
  'zika-virus',
  'yellow-fever-virus',
  'west-nile-virus',
  'nipah-virus',
  'lassa-virus',
  'cchf-virus',
  'measles-virus',
  'rsv',
  'poliovirus-1',
  'mpox-virus',
  'variola-virus',
  'hepatitis-c-virus',
  'hantaan-virus',
  'varicella-zoster-virus',
  'epstein-barr-virus',
  'influenza-a-h1n1pdm09',
  'influenza-a-h5n1',
  'mumps-virus',
  'rubella-virus',
  'chikungunya-virus',
  'hepatitis-a-virus',
] as const;

const HUMAN_EXPANSION_ENTRIES = [
  reused({
    evidenceStatus: 'conceptual',
    id: 'marburg-virus',
    name: '마르부르크 바이러스',
    shortName: 'MARV',
    nameEn: 'Marburg virus',
    taxonomyName: 'Orthomarburgvirus marburgense',
    aliases: ['Marburg marburgvirus'],
    particleState: '성숙 필라멘트 계열 표본',
    category: 'Filoviridae · Orthomarburgvirus',
    genomeLabel: '비분절 ssRNA(-)',
    description:
      '외피·matrix와 나선형 RNP가 이어지는 마르부르크바이러스 계열 구조를 관찰해요.',
    feature: '길고 굽은 외피 필라멘트',
    morphologyTags: ['animal', 'enveloped', 'helical'],
    builder: 'filovirus',
    profileId: 'filovirus-v3.5',
    sourceIds: ['ictv-filoviridae-structure'],
    silhouette: 'filament',
    parts: ['envelope', 'spike', 'matrix', 'nucleocapsid', 'genome'],
    layers: envelopeLayers,
    displayLength: 8.2,
    sectionRadius: 0.72,
  }),
  reused({
    evidenceStatus: 'conceptual',
    id: 'rabies-virus',
    name: '광견병 바이러스',
    shortName: 'RABV',
    nameEn: 'Rabies virus',
    taxonomyName: 'Lyssavirus rabies',
    particleState: '성숙 총알형 입자',
    category: 'Lyssavirus · 신경친화성 바이러스',
    genomeLabel: '비분절 ssRNA(-)',
    description: '총알형 외피와 matrix 안쪽의 나선형 RNP 축을 관찰해요.',
    feature: '총알형 외피와 방향성 RNP',
    morphologyTags: ['animal', 'enveloped', 'helical'],
    builder: 'vsv',
    profileId: 'bullet-rabies',
    sourceIds: ['ictv-rhabdoviridae'],
    silhouette: 'bullet',
    parts: ['envelope', 'spike', 'matrix', 'nucleocapsid', 'genome'],
    layers: envelopeLayers,
    displayLength: 5.4,
    sectionRadius: 1.9,
  }),
  humanRnp(
    {
      evidenceStatus: 'observed',
      id: 'dengue-virus',
      name: '뎅기 바이러스',
      shortName: 'DENV',
      nameEn: 'Dengue virus',
      taxonomyName: 'Orthoflavivirus denguei',
      aliases: ['뎅기열 바이러스'],
      particleState: '성숙 매끈한 외피 입자',
      category: 'Flavivirus · 모기 매개',
      genomeLabel: 'ssRNA(+)',
      description:
        '관측된 E/M 표면 shell과 정이십면체로 단정하지 않는 내부 capsid-RNA 개념 영역을 구분해요.',
      feature: '조밀한 E/M 표면 배열',
      morphologyTags: ['animal', 'enveloped', 'icosahedral'],
    },
    'flavivirus-smooth-envelope',
    ['ictv-flaviviridae', 'pdb-3j27', 'flavivirus-imperfect-symmetry'],
    false,
  ),
  humanRnp(
    {
      evidenceStatus: 'observed',
      id: 'zika-virus',
      name: '지카 바이러스',
      shortName: 'ZIKV',
      nameEn: 'Zika virus',
      taxonomyName: 'Orthoflavivirus zikaense',
      particleState: '성숙 외피 입자',
      category: 'Flavivirus · 모기 매개',
      genomeLabel: 'ssRNA(+)',
      description:
        '관측된 E/M 표면 shell과 대칭이 불확실한 내부 capsid-RNA 개념 영역을 구분해요.',
      feature: '조밀한 E 단백질 표면',
      morphologyTags: ['animal', 'enveloped', 'icosahedral'],
    },
    'flavivirus-smooth-envelope',
    ['ictv-flaviviridae', 'pdb-5ire', 'flavivirus-imperfect-symmetry'],
    false,
  ),
  humanRnp(
    {
      evidenceStatus: 'conceptual',
      id: 'yellow-fever-virus',
      name: '황열 바이러스',
      shortName: 'YFV',
      nameEn: 'Yellow fever virus',
      taxonomyName: 'Orthoflavivirus flavi',
      particleState: '성숙 외피 입자',
      category: 'Flavivirus · 모기 매개',
      genomeLabel: 'ssRNA(+)',
      description:
        '계열 공통 E/M 표면 shell과 내부 capsid-RNA 개념 영역을 구분하며, 부분 E 단백질 구조만 참고해요.',
      feature: 'flavivirus형 매끈한 외피',
      morphologyTags: ['animal', 'enveloped', 'icosahedral'],
    },
    'flavivirus-smooth-envelope',
    ['ictv-flaviviridae', 'pdb-6iw4', 'flavivirus-imperfect-symmetry'],
    false,
  ),
  humanRnp(
    {
      evidenceStatus: 'conceptual',
      id: 'west-nile-virus',
      name: '웨스트나일 바이러스',
      shortName: 'WNV',
      nameEn: 'West Nile virus',
      taxonomyName: 'Orthoflavivirus nilense',
      particleState: '성숙 계열 표본',
      category: 'Flavivirus · 조류-모기 매개',
      genomeLabel: 'ssRNA(+)',
      description:
        'West Nile virus를 계열 공통 E/M shell과 비정이십면체 내부 개념 구조로 표시해요.',
      feature: '조밀한 E/M 표면',
      morphologyTags: ['animal', 'enveloped', 'icosahedral'],
    },
    'flavivirus-smooth-envelope',
    ['ictv-flaviviridae', 'flavivirus-imperfect-symmetry'],
    false,
  ),
  humanRnp(
    {
      evidenceStatus: 'conceptual',
      id: 'nipah-virus',
      name: '니파 바이러스',
      shortName: 'NiV',
      nameEn: 'Nipah virus',
      taxonomyName: 'Henipavirus nipahense',
      particleState: '다형성 성숙 입자 표본',
      category: 'Henipavirus · 박쥐 매개 zoonosis',
      genomeLabel: '비분절 ssRNA(-)',
      description: 'G·F 표면 단백질, matrix와 나선형 RNP의 계열 관계를 관찰해요.',
      feature: '다형성 외피와 나선형 RNP',
      morphologyTags: ['animal', 'enveloped', 'helical'],
    },
    'henipavirus-nipah-pleomorphic-rnp',
    ['ictv-paramyxoviridae'],
  ),
  humanRnp(
    {
      evidenceStatus: 'conceptual',
      id: 'lassa-virus',
      name: '라싸 바이러스',
      shortName: 'LASV',
      nameEn: 'Lassa virus',
      taxonomyName: 'Mammarenavirus lassaense',
      particleState: '성숙 외피 입자 표본',
      category: 'Mammarenavirus · 설치류 매개',
      genomeLabel: '2분절 ambisense ssRNA',
      description:
        '외피와 matrix 안쪽에 두 RNP 분절이 놓이는 arenavirus 구조를 관찰해요.',
      feature: '2분절 ambisense RNP',
      morphologyTags: ['animal', 'enveloped'],
    },
    'arenavirus-lassa-segmented',
    ['ictv-arenaviridae'],
  ),
  humanRnp(
    {
      evidenceStatus: 'conceptual',
      id: 'cchf-virus',
      name: '크리미안콩고출혈열 바이러스',
      shortName: 'CCHFV',
      nameEn: 'Crimean-Congo hemorrhagic fever virus',
      taxonomyName: 'Orthonairovirus haemorrhagiae',
      particleState: '성숙 외피 입자 표본',
      category: 'Orthonairovirus · 진드기 매개',
      genomeLabel: '3분절 ssRNA(-)',
      description: 'Gn/Gc 외피와 세 RNP 분절의 Bunyavirales형 배치를 관찰해요.',
      feature: '3분절 RNA-RNP',
      morphologyTags: ['animal', 'enveloped'],
    },
    'nairovirus-cchf-trisegmented',
    ['ictv-nairoviridae'],
  ),
  humanRnp(
    {
      evidenceStatus: 'conceptual',
      id: 'measles-virus',
      name: '홍역 바이러스',
      shortName: 'MeV',
      nameEn: 'Measles virus',
      taxonomyName: 'Morbillivirus hominis',
      particleState: '다형성 성숙 입자 표본',
      category: 'Morbillivirus · 호흡기 전파',
      genomeLabel: '비분절 ssRNA(-)',
      description: 'H·F 표면 단백질과 matrix·나선형 RNP의 층 관계를 관찰해요.',
      feature: '다형성 외피와 나선형 RNP',
      morphologyTags: ['animal', 'enveloped', 'helical'],
    },
    'morbillivirus-measles-pleomorphic-rnp',
    ['ictv-paramyxoviridae'],
  ),
  humanRnp(
    {
      evidenceStatus: 'observed',
      id: 'rsv',
      name: '호흡기세포융합바이러스(RSV)',
      shortName: 'RSV',
      nameEn: 'Respiratory syncytial virus',
      taxonomyName: 'Orthopneumovirus hominis',
      particleState: '다형성 성숙 입자 표본',
      category: 'Orthopneumovirus · 호흡기 감염',
      genomeLabel: '비분절 ssRNA(-)',
      description: 'F·G 표면 단백질과 matrix·나선형 RNP를 계열 수준으로 관찰해요.',
      feature: 'F 단백질과 나선형 RNP',
      morphologyTags: ['animal', 'enveloped', 'helical'],
    },
    'pneumovirus-rsv-rnp',
    ['ictv-pneumoviridae'],
  ),
  humanRnp(
    {
      evidenceStatus: 'conceptual',
      id: 'hantaan-virus',
      name: '한탄바이러스',
      shortName: 'HTNV',
      nameEn: 'Hantaan virus',
      taxonomyName: 'Orthohantavirus hantanense',
      particleState: '성숙 외피 입자 표본',
      category: 'Orthohantavirus · 설치류 매개',
      genomeLabel: '3분절 ssRNA(-)',
      description:
        '관측된 Hantaan 외피·Gn/Gc 표면 격자와 세 RNP 분절의 계열 배치를 구분해요.',
      feature: '3분절 RNA-RNP',
      morphologyTags: ['animal', 'enveloped'],
    },
    'hantavirus-hantaan-trisegmented',
    ['ictv-hantaviridae', 'hantaan-cryo-et'],
  ),
  humanRnp(
    {
      evidenceStatus: 'conceptual',
      id: 'hepatitis-c-virus',
      name: 'C형간염 바이러스',
      shortName: 'HCV',
      nameEn: 'Hepatitis C virus',
      taxonomyName: 'Hepacivirus hominis',
      particleState: '이질적 lipoviroparticle 개념 표본',
      category: 'Hepacivirus · 혈액 매개',
      genomeLabel: 'ssRNA(+)',
      description:
        '이질적인 lipoviroparticle을 불규칙 E1/E2·lipoprotein patch와 개념 수준 내부 RNA 영역으로 표시해요.',
      feature: '이질적인 lipoviroparticle',
      morphologyTags: ['animal', 'enveloped'],
    },
    'hepacivirus-lipoviroparticle',
    ['ictv-flaviviridae', 'hcv-particle-review', 'hcv-ultrastructure'],
    false,
  ),
  humanRnp(
    {
      evidenceStatus: 'conceptual',
      id: 'mumps-virus',
      name: '유행성이하선염 바이러스',
      shortName: 'MuV',
      nameEn: 'Mumps virus',
      taxonomyName: 'Orthorubulavirus parotitidis',
      aliases: ['볼거리 바이러스'],
      particleState: '다형성 성숙 입자 표본',
      category: 'Orthorubulavirus · 호흡기 전파',
      genomeLabel: '비분절 ssRNA(-)',
      description: 'HN·F 표면 단백질과 matrix·나선형 RNP의 계열 배치를 관찰해요.',
      feature: '다형성 외피와 나선형 RNP',
      morphologyTags: ['animal', 'enveloped', 'helical'],
    },
    'orthorubulavirus-mumps-pleomorphic-rnp',
    ['ictv-paramyxoviridae'],
  ),
  humanRnp(
    {
      evidenceStatus: 'conceptual',
      id: 'rubella-virus',
      name: '풍진 바이러스',
      shortName: 'RuV',
      nameEn: 'Rubella virus',
      taxonomyName: 'Rubivirus rubellae',
      particleState: '다형성·관형 입자를 포함한 관측 표본',
      category: 'Rubivirus · 호흡기 전파',
      genomeLabel: 'ssRNA(+)',
      description:
        'E1/E2의 표면 row와 정이십면체가 아닌 grid-like capsid-RNA 조직을 관찰해요.',
      feature: 'E1/E2 row와 비정이십면체 RNA core',
      morphologyTags: ['animal', 'enveloped'],
    },
    'rubivirus-envelope-core',
    ['ictv-matonaviridae', 'rubella-cryo-et', 'rubella-helical-structure'],
    false,
  ),
  reused({
    evidenceStatus: 'conceptual',
    id: 'poliovirus-1',
    name: '폴리오바이러스 1형',
    shortName: 'PV1',
    nameEn: 'Poliovirus type 1',
    taxonomyName: 'Enterovirus C',
    particleState: '성숙 비외피 입자',
    category: 'Enterovirus · 소아마비',
    genomeLabel: 'ssRNA(+)',
    description: '작은 정이십면체 capsid와 내부 RNA를 관찰해요.',
    feature: '작은 비외피 picornavirus capsid',
    morphologyTags: ['animal', 'icosahedral'],
    builder: 'icosahedral-capsid',
    profileId: 'ico-poliovirus-1',
    sourceIds: ['ictv-picornaviridae', 'pdb-1hxs'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'genome'],
    layers: [layer('capsid', '정이십면체 capsid'), layer('genome', 'ssRNA(+)')],
    displayLength: 4,
    sectionRadius: 1.82,
  }),
  reused({
    evidenceStatus: 'conceptual',
    id: 'mpox-virus',
    name: '엠폭스 바이러스',
    shortName: 'MPXV',
    nameEn: 'Mpox virus',
    taxonomyName: 'Orthopoxvirus monkeypox',
    particleState: '성숙 입자(MV) 계열 표본',
    category: 'Orthopoxvirus · 사람 감염',
    genomeLabel: '선형 dsDNA',
    description: 'poxvirus 공통 막·아령형 core·lateral body를 관찰해요.',
    feature: '벽돌형 복합 입자',
    morphologyTags: ['animal', 'enveloped', 'complex'],
    builder: 'vaccinia',
    profileId: 'pox-mpox',
    sourceIds: ['ictv-pox'],
    silhouette: 'brick',
    parts: poxParts,
    layers: poxLayers,
    displayLength: 5.2,
    sectionRadius: 2.45,
  }),
  reused({
    evidenceStatus: 'conceptual',
    id: 'variola-virus',
    name: '천연두 바이러스',
    shortName: 'VARV',
    nameEn: 'Variola virus',
    taxonomyName: 'Orthopoxvirus variola',
    particleState: '성숙 입자(MV) 계열 표본',
    category: 'Orthopoxvirus · 박멸된 사람 병원체',
    genomeLabel: '선형 dsDNA',
    description:
      'variola의 poxvirus 공통 막·core·lateral body 관계를 보수적으로 표시해요.',
    feature: '벽돌형 복합 입자',
    morphologyTags: ['animal', 'enveloped', 'complex'],
    builder: 'vaccinia',
    profileId: 'pox-variola',
    sourceIds: ['ictv-pox'],
    silhouette: 'brick',
    parts: poxParts,
    layers: poxLayers,
    displayLength: 5.2,
    sectionRadius: 2.45,
  }),
  reused({
    evidenceStatus: 'conceptual',
    id: 'varicella-zoster-virus',
    name: '수두대상포진바이러스',
    shortName: 'VZV',
    nameEn: 'Varicella-zoster virus',
    taxonomyName: 'Varicellovirus humanalpha3',
    particleState: '성숙 외피 입자 계열 표본',
    category: 'Alphaherpesvirus · 잠복·재활성화',
    genomeLabel: '선형 dsDNA',
    description:
      '외피·tegument·정이십면체 capsid와 DNA의 herpesvirus 공통 층을 관찰해요.',
    feature: '외피와 tegument 사이의 capsid',
    morphologyTags: ['animal', 'enveloped', 'icosahedral'],
    builder: 'hsv',
    profileId: 'herpes-vzv',
    sourceIds: ['ictv-herpes'],
    silhouette: 'envelope',
    parts: herpesParts,
    layers: herpesLayers,
    displayLength: 5.3,
    sectionRadius: 2.6,
  }),
  reused({
    evidenceStatus: 'conceptual',
    id: 'epstein-barr-virus',
    name: '엡스타인-바 바이러스',
    shortName: 'EBV',
    nameEn: 'Epstein-Barr virus',
    taxonomyName: 'Lymphocryptovirus humangamma4',
    particleState: '성숙 외피 입자 계열 표본',
    category: 'Gammaherpesvirus · 잠복 감염',
    genomeLabel: '선형 dsDNA',
    description: '외피·tegument·capsid·DNA의 herpesvirus 공통 층을 관찰해요.',
    feature: '두꺼운 tegument와 정이십면체 capsid',
    morphologyTags: ['animal', 'enveloped', 'icosahedral'],
    builder: 'hsv',
    profileId: 'herpes-ebv',
    sourceIds: ['ictv-herpes'],
    silhouette: 'envelope',
    parts: herpesParts,
    layers: herpesLayers,
    displayLength: 5.3,
    sectionRadius: 2.6,
  }),
  reused({
    evidenceStatus: 'conceptual',
    id: 'influenza-a-h1n1pdm09',
    name: '인플루엔자 A(H1N1)pdm09',
    shortName: 'H1N1pdm09',
    nameEn: 'Influenza A(H1N1)pdm09 virus',
    taxonomyName: 'Alphainfluenzavirus influenzae',
    particleState: '성숙 구형 계열 표본',
    category: 'Influenza A · 2009 pandemic lineage',
    genomeLabel: '8분절 ssRNA(-)',
    description: 'HA·NA·M2와 M1 안쪽의 여덟 vRNP를 계통 공통 구조로 관찰해요.',
    feature: '8개 vRNP와 HA/NA 표면',
    morphologyTags: ['animal', 'enveloped'],
    builder: 'influenza',
    profileId: 'influenza-h1n1pdm09',
    sourceIds: ['ictv-influenza', 'influenza-quant'],
    silhouette: 'envelope',
    parts: influenzaParts,
    layers: influenzaLayers,
    displayLength: 4.8,
    sectionRadius: 2.45,
  }),
  reused({
    evidenceStatus: 'conceptual',
    id: 'influenza-a-h5n1',
    name: '인플루엔자 A(H5N1)',
    shortName: 'H5N1',
    nameEn: 'Influenza A(H5N1) virus',
    taxonomyName: 'Alphainfluenzavirus influenzae',
    particleState: '성숙 구형 계열 표본',
    category: 'Influenza A · 조류 유래 zoonosis',
    genomeLabel: '8분절 ssRNA(-)',
    description:
      'H5·N1 항원형을 외형 차이로 과장하지 않고 공통 여덟 vRNP 구조를 관찰해요.',
    feature: '8개 vRNP와 HA/NA 표면',
    morphologyTags: ['animal', 'enveloped'],
    builder: 'influenza',
    profileId: 'influenza-h5n1',
    sourceIds: ['ictv-influenza', 'influenza-quant'],
    silhouette: 'envelope',
    parts: influenzaParts,
    layers: influenzaLayers,
    displayLength: 4.8,
    sectionRadius: 2.45,
  }),
  reused({
    evidenceStatus: 'observed',
    id: 'chikungunya-virus',
    name: '치쿤구니야 바이러스',
    shortName: 'CHIKV',
    nameEn: 'Chikungunya virus',
    taxonomyName: 'Alphavirus chikungunya',
    particleState: '성숙 외피 입자',
    category: 'Alphavirus · 모기 매개',
    genomeLabel: 'ssRNA(+)',
    description: 'E1/E2 spike와 정이십면체 nucleocapsid의 방사형 대응을 관찰해요.',
    feature: '정렬된 E1/E2 외피 lattice',
    morphologyTags: ['animal', 'enveloped', 'icosahedral'],
    builder: 'alphavirus',
    profileId: 'enveloped-alphavirus-chikungunya',
    sourceIds: ['ictv-togaviridae', 'pdb-6nk5'],
    silhouette: 'envelope',
    parts: alphaParts,
    layers: alphaLayers,
    displayLength: 4.8,
    sectionRadius: 2.3,
  }),
  reused({
    evidenceStatus: 'conceptual',
    id: 'hepatitis-a-virus',
    name: 'A형간염 바이러스',
    shortName: 'HAV',
    nameEn: 'Hepatitis A virus',
    taxonomyName: 'Hepatovirus A',
    particleState: '성숙 비외피 입자',
    category: 'Hepatovirus · 분변-경구 전파',
    genomeLabel: 'ssRNA(+)',
    description: '작은 비외피 capsid와 내부 양성가닥 RNA를 관찰해요.',
    feature: '매끈한 picornavirus형 capsid',
    morphologyTags: ['animal', 'icosahedral'],
    builder: 'icosahedral-capsid',
    profileId: 'ico-hepatitis-a',
    sourceIds: ['ictv-picornaviridae', 'pdb-4qpi'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'genome'],
    layers: [layer('capsid', '정이십면체 capsid'), layer('genome', 'ssRNA(+)')],
    displayLength: 4,
    sectionRadius: 1.82,
  }),
] as const;

export const HUMAN_EXPANSION_CATALOG = HUMAN_EXPANSION_IDS.map((id) => {
  const entry = HUMAN_EXPANSION_ENTRIES.find((candidate) => candidate.id === id);
  if (!entry) throw new Error(`Missing v4.8.5 human catalog entry: ${id}`);
  return entry;
});
