import { defineVirus, layer } from '../shared';

export const PHAGE_CATALOG = [
  defineVirus({
    evidenceStatus: 'observed',
    id: 'phix174',
    name: 'ΦX174 파지',
    shortName: 'ΦX174',
    nameEn: 'Bacteriophage phiX174',
    aliases: ['phi X174'],
    particleState: '성숙 입자',
    category: '꼭짓점 돌기형 소형 파지',
    genomeLabel: '원형 ssDNA',
    description: '작은 T=1 껍질과 열두 꼭짓점의 G 단백질 돌출 위치를 강조해요.',
    feature: '열두 꼭짓점 돌기',
    morphologyTags: ['phage', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'spike', 'genome'],
    layers: [
      layer('capsid', 'T=1 캡시드'),
      layer('surface-protein', '꼭짓점 돌기'),
      layer('genome', 'ssDNA'),
    ],
    sourceIds: ['pdb-2bpa'],
    modelBuilder: 'generic-icosahedral',
    geometryProfileId: 'ico-spiked-t1',
    simplifications: [
      '외부 조립 보조 단백질은 성숙 입자에서 제외했어요.',
      '꼭짓점 통로는 돌기 방향으로만 표시했어요.',
    ],
    displayLength: 3.7,
    sectionRadius: 1.85,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'qbeta',
    name: 'Qβ 파지',
    shortName: 'Qβ',
    nameEn: 'Qbeta bacteriophage',
    aliases: ['Q beta'],
    particleState: '성숙 RNA 입자',
    category: '작은 T=3 RNA 파지',
    genomeLabel: 'ssRNA(+)',
    description: 'T=3 피복 배열과 한쪽의 비대칭 성숙 단백질 위치를 함께 살펴봐요.',
    feature: 'T=3 껍질과 비대칭 부위',
    morphologyTags: ['phage', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'maturation-protein', 'genome'],
    layers: [layer('capsid', 'T=3 피복'), layer('genome', 'ssRNA(+)')],
    sourceIds: ['pdb-1qbe'],
    modelBuilder: 'generic-icosahedral',
    geometryProfileId: 'ico-rna-t3-asymmetric',
    simplifications: [
      'RNA 접힘은 내부 개념 곡선이에요.',
      '비대칭 단백질의 방향만 구분했어요.',
    ],
    displayLength: 3.8,
    sectionRadius: 1.9,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'phi29',
    name: 'Φ29 파지',
    shortName: 'Φ29',
    nameEn: 'Bacteriophage phi29',
    particleState: '성숙 유전체 보유 입자',
    category: '길쭉한 머리·짧은 꼬리 파지',
    genomeLabel: 'dsDNA',
    description: '길쭉한 머리와 짧은 비수축형 꼬리, 목 둘레의 부속 구조를 구분해요.',
    feature: 'prolate 머리와 짧은 꼬리',
    morphologyTags: ['phage', 'icosahedral'],
    silhouette: 'phage',
    parts: ['capsid', 'capsomer', 'portal', 'inner-tube', 'tail-fiber', 'genome'],
    layers: [
      layer('capsid', '길쭉한 머리'),
      layer('tail', '짧은 꼬리'),
      layer('genome', 'dsDNA'),
    ],
    sourceIds: ['pdb-6qvk'],
    modelBuilder: 'generic-phage',
    geometryProfileId: 'phage-prolate-short',
    simplifications: [
      '포장 모터의 분자 세부는 생략했어요.',
      '목 섬유는 확인 가능한 방사 방향만 표시했어요.',
    ],
    displayLength: 5.2,
    sectionRadius: 1.55,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'p22',
    name: 'P22 파지',
    shortName: 'P22',
    nameEn: 'Bacteriophage P22',
    particleState: '성숙 입자',
    category: 'tailspike 보유 짧은 꼬리 파지',
    genomeLabel: 'dsDNA',
    description: '다면체 머리 아래의 짧은 꼬리 허브와 여섯 개 tailspike를 강조해요.',
    feature: '여섯 tailspike 꼬리 장치',
    morphologyTags: ['phage', 'icosahedral'],
    silhouette: 'phage',
    parts: ['capsid', 'capsomer', 'portal', 'tailspike', 'genome'],
    layers: [
      layer('capsid', '성숙 캡시드'),
      layer('tail', '꼬리 허브·tailspike'),
      layer('genome', 'dsDNA'),
    ],
    sourceIds: ['pdb-5uu5', 'pdb-8tvr'],
    modelBuilder: 'generic-phage',
    geometryProfileId: 'phage-p22-tailspike',
    simplifications: [
      'ejection 단백질의 내부 배치는 생략했어요.',
      'tailspike 도메인은 굵은 분절로 줄였어요.',
    ],
    displayLength: 4.8,
    sectionRadius: 1.65,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'hk97',
    name: 'HK97 파지',
    shortName: 'HK97',
    nameEn: 'Bacteriophage HK97',
    particleState: '성숙 Head II 중심 재구성',
    category: '얇은 T=7 성숙 캡시드 파지',
    genomeLabel: 'dsDNA',
    description:
      '교차결합된 얇은 T=7 머리 표면을 중심으로 목과 꼬리를 단순화해 보여줘요.',
    feature: '연결고리형 성숙 머리 표면',
    morphologyTags: ['phage', 'icosahedral'],
    silhouette: 'phage',
    parts: ['capsid', 'capsomer', 'neck', 'flexible-tail', 'genome'],
    layers: [
      layer('capsid', 'Head II 캡시드'),
      layer('tail', '비수축형 꼬리'),
      layer('genome', 'dsDNA 개념도'),
    ],
    sourceIds: ['pdb-2ft1'],
    modelBuilder: 'generic-phage',
    geometryProfileId: 'phage-hk97-thin',
    simplifications: [
      'Head II 구조 근거가 가장 강하며 꼬리는 계열 수준으로 단순화했어요.',
      '공유결합 연결망을 개별 결합으로 그리지 않았어요.',
    ],
    displayLength: 6.6,
    sectionRadius: 1.6,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 't5',
    name: 'T5 파지',
    shortName: 'T5',
    nameEn: 'Bacteriophage T5',
    particleState: '성숙 입자 형태',
    category: '긴 비수축형 꼬리 파지',
    genomeLabel: 'dsDNA',
    description: '큰 머리와 매우 긴 비수축형 꼬리, 말단 섬유 복합체를 구분해요.',
    feature: '긴 꼬리와 복잡한 말단',
    morphologyTags: ['phage', 'icosahedral'],
    silhouette: 'phage',
    parts: ['capsid', 'capsomer', 'neck', 'flexible-tail', 'tail-fiber', 'genome'],
    layers: [
      layer('capsid', '큰 머리'),
      layer('tail', '긴 비수축형 꼬리'),
      layer('genome', 'dsDNA'),
    ],
    sourceIds: ['pdb-8zvi'],
    modelBuilder: 'generic-phage',
    geometryProfileId: 'phage-long-t5',
    simplifications: [
      '꼬리 반복 단위를 연속 관과 링으로 줄였어요.',
      '말단 단백질은 형태 관계만 표시했어요.',
    ],
    displayLength: 8.2,
    sectionRadius: 1.7,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 't1',
    name: 'T1 파지',
    shortName: 'T1',
    nameEn: 'Bacteriophage T1',
    particleState: '성숙 입자 형태',
    category: '긴 비수축형 꼬리 파지',
    genomeLabel: 'dsDNA',
    description: '둥근 머리와 길고 가는 꼬리, 끝의 작은 수용체 결합 섬유를 보여줘요.',
    feature: '가는 긴 꼬리와 작은 말단',
    morphologyTags: ['phage', 'icosahedral'],
    silhouette: 'phage',
    parts: ['capsid', 'capsomer', 'neck', 'flexible-tail', 'tail-fiber', 'genome'],
    layers: [
      layer('capsid', '캡시드'),
      layer('tail', '긴 꼬리·말단'),
      layer('genome', 'dsDNA'),
    ],
    sourceIds: ['pdb-9l01'],
    modelBuilder: 'generic-phage',
    geometryProfileId: 'phage-long-t1',
    simplifications: [
      'T5보다 단순한 말단 윤곽을 중심으로 표현했어요.',
      '꼬리의 실제 반복 수는 줄였어요.',
    ],
    displayLength: 7.8,
    sectionRadius: 1.55,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'prd1',
    name: 'PRD1 파지',
    shortName: 'PRD1',
    nameEn: 'Bacteriophage PRD1',
    particleState: '성숙 막 보유 입자',
    category: '내부 막 보유 다면체 파지',
    genomeLabel: 'dsDNA',
    description:
      '단백질 캡시드 안쪽 막과 꼭짓점 스파이크가 함께 있는 층 구조를 보여줘요.',
    feature: '캡시드 안쪽의 막',
    morphologyTags: ['phage', 'icosahedral', 'complex'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'inner-membrane', 'spike', 'genome'],
    layers: [
      layer('capsid', '외부 캡시드'),
      layer('inner-membrane', '내부 막'),
      layer('surface-protein', '꼭짓점 구조'),
      layer('genome', 'dsDNA'),
    ],
    sourceIds: ['pdb-1w8x'],
    modelBuilder: 'generic-layered',
    geometryProfileId: 'layered-prd1',
    simplifications: [
      '막의 지질 조성과 포털 세부는 표시하지 않았어요.',
      '꼭짓점 구조 수와 길이를 화면용으로 줄였어요.',
    ],
    displayLength: 4.7,
    sectionRadius: 2.15,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'phi6',
    name: 'Φ6 파지',
    shortName: 'Φ6',
    nameEn: 'Bacteriophage phi6',
    particleState: '성숙 외피 입자',
    category: '외피·다층 코어 RNA 파지',
    genomeLabel: '3분절 dsRNA',
    description:
      '바깥 막과 표면 단백질, 그 안의 다층 코어를 차례로 분리해 볼 수 있어요.',
    feature: '외피와 dsRNA 코어',
    morphologyTags: ['phage', 'enveloped', 'complex'],
    silhouette: 'envelope',
    parts: ['envelope', 'spike', 'outer-capsid', 'core-capsid', 'genome'],
    layers: [
      layer('envelope', '지질 외피'),
      layer('surface-protein', '표면 단백질'),
      layer('outer-capsid', '외부 코어층'),
      layer('core-capsid', '내부 코어'),
      layer('genome', '3분절 dsRNA'),
    ],
    sourceIds: ['ictv-cystoviridae'],
    modelBuilder: 'generic-enveloped',
    geometryProfileId: 'enveloped-phi6',
    simplifications: [
      '외피의 불규칙성은 완만한 구형으로 줄였어요.',
      '세 RNA 분절은 서로 다른 내부 선으로 표시했어요.',
    ],
    displayLength: 4.8,
    sectionRadius: 2.3,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'pm2',
    name: 'PM2 파지',
    shortName: 'PM2',
    nameEn: 'Bacteriophage PM2',
    particleState: '성숙 막 보유 입자',
    category: '내부 막 보유 다면체 파지',
    genomeLabel: '원형 dsDNA',
    description: '다면체 단백질 껍질과 내부 막, 꼭짓점 복합체의 관계를 살펴봐요.',
    feature: '내부 막과 꼭짓점 단백질',
    morphologyTags: ['phage', 'icosahedral', 'complex'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'inner-membrane', 'spike', 'genome'],
    layers: [
      layer('capsid', '외부 캡시드'),
      layer('inner-membrane', '내부 막'),
      layer('surface-protein', '꼭짓점 복합체'),
      layer('genome', '원형 dsDNA'),
    ],
    sourceIds: ['ictv-corticoviridae'],
    modelBuilder: 'generic-layered',
    geometryProfileId: 'layered-pm2',
    simplifications: [
      'PRD1과 공유되는 층 원리를 유지하되 더 둥근 표면으로 표현했어요.',
      '내부 막의 단백질은 생략했어요.',
    ],
    displayLength: 4.5,
    sectionRadius: 2.05,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'ap205',
    name: 'AP205 파지',
    shortName: 'AP205',
    nameEn: 'Acinetobacter phage AP205',
    particleState: '조립 캡시드 구조 참고',
    category: '작은 T=3 RNA 파지',
    genomeLabel: 'ssRNA(+)',
    description:
      '작은 T=3 캡시드의 피복 단백질 배열과 RNA가 놓이는 내부 공간을 보여줘요.',
    feature: '조밀한 T=3 피복 배열',
    morphologyTags: ['phage', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'genome'],
    layers: [layer('capsid', 'T=3 캡시드'), layer('genome', 'ssRNA(+) 개념도')],
    sourceIds: ['pdb-5jzr'],
    modelBuilder: 'generic-icosahedral',
    geometryProfileId: 'ico-ap205-compact',
    simplifications: [
      'NMR 조립 구조를 원자 표면으로 재현하지 않았어요.',
      'RNA는 실측 패킹이 아닌 내부 위치 개념도예요.',
    ],
    displayLength: 3.6,
    sectionRadius: 1.8,
  }),
] as const;
