import { defineVirus, layer } from '../shared';

export const PLANT_CATALOG = [
  defineVirus({
    evidenceStatus: 'observed',
    id: 'ccmv',
    name: '동부콩 퇴록얼룩바이러스',
    shortName: 'CCMV',
    nameEn: 'Cowpea chlorotic mottle virus',
    particleState: 'native compact virion',
    category: 'T=3 구형 식물 바이러스',
    genomeLabel: '3분절 ssRNA(+)',
    description:
      'native compact 상태의 T=3 껍질과 오각·육각 환경의 표면 단위를 보여줘요.',
    feature: 'native compact T=3 배열',
    morphologyTags: ['plant', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'genome'],
    layers: [layer('capsid', 'T=3 캡시드'), layer('genome', '분절 ssRNA(+)')],
    sourceIds: ['pdb-1cwp'],
    modelBuilder: 'icosahedral-capsid',
    geometryProfileId: 'ico-plant-t3-soft',
    simplifications: [
      '팽창 상태가 아닌 native compact 구조를 선택했어요.',
      'RNA는 껍질 안쪽 분포만 개념화했어요.',
    ],
    displayLength: 4,
    sectionRadius: 2,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'bmv',
    name: '브롬모자이크바이러스',
    shortName: 'BMV',
    nameEn: 'Brome mosaic virus',
    particleState: 'native compact virion',
    category: 'T=3 구형 식물 바이러스',
    genomeLabel: '3분절 ssRNA(+)',
    description:
      'CCMV와 닮은 compact T=3 껍질을 유지하면서 더 얕은 표면 골을 표시해요.',
    feature: 'compact 껍질과 얕은 표면 골',
    morphologyTags: ['plant', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'genome'],
    layers: [layer('capsid', 'T=3 캡시드'), layer('genome', '분절 ssRNA(+)')],
    sourceIds: ['pdb-1js9'],
    modelBuilder: 'icosahedral-capsid',
    geometryProfileId: 'ico-plant-t3-compact',
    simplifications: [
      'CCMV와의 구조적 유사성을 의도적으로 유지했어요.',
      'RNA 종류별 입자 차이는 한 모델에 합치지 않았어요.',
    ],
    displayLength: 4,
    sectionRadius: 1.98,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'cpmv',
    name: '동부콩모자이크바이러스',
    shortName: 'CPMV',
    nameEn: 'Cowpea mosaic virus',
    particleState: 'genome-containing virion',
    category: 'pseudo T=3 구형 식물 바이러스',
    genomeLabel: '2분절 ssRNA(+)',
    description:
      '서로 다른 큰·작은 피복 단위가 만드는 pseudo T=3 표면 구획을 강조해요.',
    feature: '큰·작은 피복 단위 조합',
    morphologyTags: ['plant', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'genome'],
    layers: [layer('capsid', 'pseudo T=3 캡시드'), layer('genome', '분절 ssRNA(+)')],
    sourceIds: ['pdb-1ny7', 'pdb-5a33'],
    modelBuilder: 'icosahedral-capsid',
    geometryProfileId: 'ico-plant-pseudo-t3',
    simplifications: [
      '큰·작은 단위의 구역을 두 크기의 표면 기하로 줄였어요.',
      '두 RNA가 각각 포장되는 사실을 한 입자 보기로 일반화했어요.',
    ],
    displayLength: 4.2,
    sectionRadius: 2.1,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'tbsv',
    name: '토마토덤불위축바이러스',
    shortName: 'TBSV',
    nameEn: 'Tomato bushy stunt virus',
    particleState: '성숙 virion',
    category: '돌출 도메인형 T=3 식물 바이러스',
    genomeLabel: 'ssRNA(+)',
    description: 'T=3 껍질 바깥으로 드러나는 돌출 영역과 안쪽 shell 영역을 구분해요.',
    feature: '표면 돌출 도메인',
    morphologyTags: ['plant', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'genome'],
    layers: [
      layer('capsid', 'T=3 shell'),
      layer('surface-protein', '돌출 도메인'),
      layer('genome', 'ssRNA(+)'),
    ],
    sourceIds: ['pdb-2tbv'],
    modelBuilder: 'icosahedral-capsid',
    geometryProfileId: 'ico-plant-t3-protruding',
    simplifications: [
      '돌출 도메인을 개별 원자 표면 대신 굵은 반복 단위로 표시했어요.',
      '유전체 패킹은 개념도예요.',
    ],
    displayLength: 4.2,
    sectionRadius: 2.05,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'stmv',
    name: '위성담배모자이크바이러스',
    shortName: 'STMV',
    nameEn: 'Satellite tobacco mosaic virus',
    particleState: '성숙 위성바이러스 입자',
    category: '매우 작은 T=1 위성바이러스',
    genomeLabel: 'ssRNA(+)',
    description: 'TMV와 달리 작은 정이십면체 입자이며 조밀한 T=1 껍질을 가져요.',
    feature: '작은 T=1 위성 입자',
    morphologyTags: ['plant', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'genome'],
    layers: [layer('capsid', 'T=1 캡시드'), layer('genome', 'ssRNA(+)')],
    sourceIds: ['pdb-1a34'],
    modelBuilder: 'icosahedral-capsid',
    geometryProfileId: 'ico-stmv-small',
    simplifications: [
      '실제 상대 크기는 카드 간 화면 확대 때문에 직접 비교할 수 없어요.',
      'RNA 접힘은 생략했어요.',
    ],
    displayLength: 3.4,
    sectionRadius: 1.7,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'cmv-fny',
    name: '오이모자이크바이러스 Fny',
    shortName: 'CMV Fny',
    nameEn: 'Cucumber mosaic virus Fny',
    particleState: 'Fny strain virion',
    category: 'T=3 구형 식물 바이러스',
    genomeLabel: '3분절 ssRNA(+)',
    description: '선택한 Fny 균주의 T=3 피복 배열과 안쪽 RNA 공간을 표시해요.',
    feature: 'Fny 균주 T=3 표면',
    morphologyTags: ['plant', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'genome'],
    layers: [layer('capsid', 'T=3 피복'), layer('genome', '분절 ssRNA(+)')],
    sourceIds: ['pdb-1f15'],
    modelBuilder: 'icosahedral-capsid',
    geometryProfileId: 'ico-cmv-fny',
    simplifications: [
      'Fny 균주 구조로 범위를 한정했어요.',
      '서로 다른 RNA 입자를 한 화면 관계도로 단순화했어요.',
    ],
    displayLength: 4,
    sectionRadius: 2,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'tymv',
    name: '순무황화모자이크바이러스',
    shortName: 'TYMV',
    nameEn: 'Turnip yellow mosaic virus',
    particleState: '성숙 virion',
    category: '조밀한 T=3 식물 바이러스',
    genomeLabel: 'ssRNA(+)',
    description:
      '둥글게 이어진 T=3 표면 단위와 내부 RNA가 껍질 가까이 놓이는 관계를 보여줘요.',
    feature: '조밀한 T=3 표면 단위',
    morphologyTags: ['plant', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'genome'],
    layers: [layer('capsid', 'T=3 캡시드'), layer('genome', 'ssRNA(+)')],
    sourceIds: ['pdb-1auy'],
    modelBuilder: 'icosahedral-capsid',
    geometryProfileId: 'ico-tymv-dense',
    simplifications: [
      '표면 단위 밀도를 렌더 예산에 맞게 줄였어요.',
      '내부 RNA 위치는 방사형 분포 개념도예요.',
    ],
    displayLength: 4,
    sectionRadius: 2,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'pvx',
    name: '감자바이러스 X',
    shortName: 'PVX',
    nameEn: 'Potato virus X',
    particleState: '유연한 성숙 filament',
    category: '유연한 나선형 식물 바이러스',
    genomeLabel: 'ssRNA(+)',
    description: '부드럽게 휘는 필라멘트 표면의 나선 피복과 중심 RNA 경로를 보여줘요.',
    feature: '유연한 나선 필라멘트',
    morphologyTags: ['plant', 'helical'],
    silhouette: 'filament',
    parts: ['capsid', 'coat-protein', 'terminal-protein', 'genome'],
    layers: [layer('capsid', '나선 피복'), layer('genome', 'ssRNA(+)')],
    sourceIds: ['emd-pvx'],
    modelBuilder: 'generic-filament',
    geometryProfileId: 'filament-pvx-flexible',
    simplifications: [
      '전체 길이를 화면에 맞게 크게 줄였어요.',
      '낮은 진폭의 굽힘은 관찰용 연출이에요.',
    ],
    displayLength: 8,
    sectionRadius: 0.62,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'papmv',
    name: '파파야모자이크바이러스',
    shortName: 'PapMV',
    nameEn: 'Papaya mosaic virus',
    particleState: '피복 구조 기반 filament',
    category: '유연한 나선형 식물 바이러스',
    genomeLabel: 'ssRNA(+)',
    description: '피복 단백질이 이루는 굵은 나선 띠와 유연한 필라멘트 윤곽을 살펴봐요.',
    feature: '굵은 나선 피복 띠',
    morphologyTags: ['plant', 'helical'],
    silhouette: 'filament',
    parts: ['capsid', 'coat-protein', 'terminal-protein', 'genome'],
    layers: [layer('capsid', '나선 피복'), layer('genome', 'ssRNA(+) 개념도')],
    sourceIds: ['pdb-4dox', 'ictv-alphaflexiviridae'],
    modelBuilder: 'generic-filament',
    geometryProfileId: 'filament-papmv-flexible',
    simplifications: [
      '단백질 구조와 계열 형태를 결합한 절차 재구성이에요.',
      '유전체 원자 배치는 재현하지 않았어요.',
    ],
    displayLength: 7.6,
    sectionRadius: 0.72,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'pvy',
    name: '감자바이러스 Y',
    shortName: 'PVY',
    nameEn: 'Potato virus Y',
    particleState: '성숙 flexible filament',
    category: '가늘고 유연한 potyvirus',
    genomeLabel: 'ssRNA(+)',
    description: 'PVX보다 가늘고 긴 potyvirus형 나선 피복과 말단 방향성을 보여줘요.',
    feature: '가늘고 긴 potyvirus 피복',
    morphologyTags: ['plant', 'helical'],
    silhouette: 'filament',
    parts: ['capsid', 'coat-protein', 'terminal-protein', 'genome'],
    layers: [layer('capsid', '나선 피복'), layer('genome', 'ssRNA(+)')],
    sourceIds: ['pdb-6hxx'],
    modelBuilder: 'generic-filament',
    geometryProfileId: 'filament-pvy-thin',
    simplifications: [
      '실제 길이를 축소하고 나선 반복 수를 줄였어요.',
      '말단 차이는 색이 아닌 형상 크기로만 구분했어요.',
    ],
    displayLength: 8.4,
    sectionRadius: 0.5,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'camv',
    name: '콜리플라워모자이크바이러스',
    shortName: 'CaMV',
    nameEn: 'Cauliflower mosaic virus',
    particleState: '성숙 isometric virion',
    category: '구형 pararetrovirus',
    genomeLabel: '원형 dsDNA-RT',
    description: '표면이 비교적 둥근 다면체 피복과 중심 DNA 공간을 단순화해 보여줘요.',
    feature: '둥근 등축성 피복',
    morphologyTags: ['plant', 'icosahedral'],
    silhouette: 'polyhedron',
    parts: ['capsid', 'capsomer', 'surface-domain', 'genome'],
    layers: [layer('capsid', '등축성 캡시드'), layer('genome', '원형 dsDNA-RT')],
    sourceIds: ['ictv-caulimoviridae'],
    modelBuilder: 'icosahedral-capsid',
    geometryProfileId: 'ico-camv-rounded',
    simplifications: [
      '완전한 고해상도 virion 좌표가 아닌 공식 형태 설명 기반이에요.',
      '내부 단백질과 DNA 패킹은 개념도예요.',
    ],
    displayLength: 4.2,
    sectionRadius: 2.05,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'maize-streak',
    name: '옥수수줄무늬바이러스',
    shortName: 'MSV',
    nameEn: 'Maize streak virus',
    aliases: ['Maize streak'],
    particleState: 'geminate virion',
    category: '쌍둥이형 geminivirus',
    genomeLabel: '원형 ssDNA',
    description:
      '두 불완전한 정이십면체가 맞닿은 geminate 윤곽과 연결 부위를 보여줘요.',
    feature: '두 캡시드가 맞닿은 geminate 형태',
    morphologyTags: ['plant', 'icosahedral', 'complex'],
    silhouette: 'geminate',
    parts: ['capsid', 'capsomer', 'geminate-bridge', 'genome'],
    layers: [layer('capsid', '쌍둥이형 캡시드'), layer('genome', '원형 ssDNA')],
    sourceIds: ['ictv-geminiviridae'],
    modelBuilder: 'generic-geminate',
    geometryProfileId: 'geminate-msv',
    simplifications: [
      '두 반쪽의 접합부를 연속 단백질 덩어리로 줄였어요.',
      '원형 DNA는 두 엽 내부의 개념 경로예요.',
    ],
    displayLength: 5.2,
    sectionRadius: 1.55,
  }),
  defineVirus({
    evidenceStatus: 'observed',
    id: 'tylcv',
    name: '토마토황화잎말림바이러스',
    shortName: 'TYLCV',
    nameEn: 'Tomato yellow leaf curl virus',
    particleState: 'geminate virion',
    category: '쌍둥이형 geminivirus',
    genomeLabel: '원형 ssDNA',
    description: '두 엽이 이루는 geminate 입자와 접합부 주변의 반복 단위를 살펴봐요.',
    feature: '좁은 접합부의 geminate 입자',
    morphologyTags: ['plant', 'icosahedral', 'complex'],
    silhouette: 'geminate',
    parts: ['capsid', 'capsomer', 'geminate-bridge', 'genome'],
    layers: [layer('capsid', '쌍둥이형 캡시드'), layer('genome', '원형 ssDNA')],
    sourceIds: ['ictv-geminiviridae'],
    modelBuilder: 'generic-geminate',
    geometryProfileId: 'geminate-tylcv',
    simplifications: [
      'MSV와 공유되는 geminate 원리를 유지했어요.',
      '종별 표면 차이는 확인 가능한 접합 비율과 반복 밀도로만 표현했어요.',
    ],
    displayLength: 5,
    sectionRadius: 1.5,
  }),
] as const;
